### ISSUE TITLE
[Bug]: code-oss serve-web return ENOENT

### ISSUE THREAD

**Issue by lzif** [termux-user-repository/tur#1033]
### Problem description

When attempting to run the `code-oss serve-web` command on Termux, an error is encountered, preventing successful execution. The error message is as follows:
`spawn /data/data/com.termux/files/usr/lib/code-oss/bin/code-tunnel-oss ENOENT`

### What steps will reproduce the bug?

Need to build the CLI and include it in package (`cargo build` in the CLI folder).

[Sources](https://github.com/microsoft/vscode/issues/191166)

### What is the expected behavior?

The code-oss serve-web command should start the web server without any errors.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=14867
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
libass/stable 0.17.2 aarch64 [upgradable from: 0.17.1]
libnghttp2/stable 1.62.1 aarch64 [upgradable from: 1.62.0]
termux-tools version:
1.42.1
Android version:
11
Kernel build information:
Linux localhost 4.19.127-g8a0741fcbb1a-dirty #1 SMP PREEMPT Fri Mar 24 18:07:42 CST 2023 aarch64 Android
Device manufacturer:
INFINIX MOBILITY LIMITED
Device model:
Infinix X688B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.styling versionCode:31
```

**Comment by licy183** [comment]
I don't know whether it works or not, as `code-tunnel-oss` is not written for Android, and Android isn't treated as a supported platform...

**Comment by licy183** [comment]
This cannot be used because it is not supported for Android.

```
~ $ code-oss serve-web

[2024-05-20 11:05:35] error platform not currently supported: android x86_64
```

It is possible to patch it to linux, but the remote server is not open-sourced and it is compiled for GNU libc rather than Bionic libc, so it will not work on Termux.
