### ISSUE TITLE
[Package]: Compile wine-devel with WoW64 support

### ISSUE THREAD

**Issue by chaitan3** [termux-user-repository/tur#1050]
### Name

wine-devel

### Source code URL

https://gitlab.freedesktop.org/wine/wine

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

Wine 9.0 supports running 32-bit x86 programs on arm64 using an external dependency like FEX:

https://gitlab.winehq.org/wine/wine/-/releases/wine-9.0#arm64

wine-devel should be compiled with WoW64 support in order to enable this to be tested and used. This bypasses the need for a program like hangover and in future could also allow 64-bit x86 programs to run.

**Comment by hansm629** [comment]
@chaitan3 
What about enabling `ARM64EC`?
If `ARM64EC` is activated, is it possible to run x86 and x64 programs in wine without `box64`?

**Comment by chaitan3** [comment]
When arm64ec is complete, it should be possible. Wine devs are still working on it. According to Hangover's dev, it might happen with wine 10.0.
