### ISSUE TITLE
[Package]: sdlpal

### ISSUE THREAD

**Issue by spz2020** [termux-user-repository/tur#1053]
### Name

sdlpal

### Source code URL

https://github.com/sdlpal/sdlpal

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

It looks like the software compiled successfully
![Screenshot_2024-05-28-20-17-13-49_00df01c412509efb9bd6450c382822af](https://github.com/termux-user-repository/tur/assets/74664513/726bcf2e-c5f6-49ab-9d71-843c58651802)
![Screenshot_2024-05-28-20-17-21-42_00df01c412509efb9bd6450c382822af](https://github.com/termux-user-repository/tur/assets/74664513/5f9db93a-a382-444b-997b-3df446fa15e5)
But the keyboard doesn't seem to work

**Comment by spz2020** [comment]
Update: After I change the name of the folder to English, everything looks normal

https://github.com/termux-user-repository/tur/assets/74664513/a3fe6efb-6882-4bee-8423-3e3296c9f780

**Comment by licy183** [comment]
I'm currently doing an internship and a bit busy. Feel free to submit a Pull Request.

**Comment by licy183** [comment]
Please test the debs in https://github.com/termux-user-repository/tur/actions/runs/10676515167. Thanks!
