### ISSUE TITLE
[Package]: Add openjdk-21

### ISSUE THREAD

**Issue by kairusds** [termux-user-repository/tur#1078]
### Name

openjdk-21

### Home page URL

https://openjdk.org/projects/jdk/

### Source code URL

https://github.com/openjdk/jdk/tree/jdk-21%2B35

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by licy183** [comment]
`openjdk-21` has been added in the main repository
