### ISSUE TITLE
[Package]: obsidian 

### ISSUE THREAD

**Issue by shukryshuk** [termux-user-repository/tur#1093]
### Name

obsidian

### Home page URL

https://obsidian.md

### Source code URL

https://github.com/obsidianmd

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by IntinteDAO** [comment]
> Obsidian is not open source software and this repo DOES NOT contain the source code of Obsidian.

To port apps for Termux you need a source code in most cases

**Comment by licy183** [comment]
It is not open-source so it is not possible to build.
