### ISSUE TITLE
[Bug]: Invalid references in zink aarch64 packages

### ISSUE THREAD

**Issue by kripper** [termux-user-repository/tur#1193]
The command:

`~ $ pkg install mesa-zink virglrenderer-mesa-zink vulkan-loader-android`

Generates this error:

```
E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/fbe2a827-a41b-48d9-bafa-ce6f352a679c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240913/us-east-1/s3/aws4_request&X-Amz-Date=20240913T050547Z&X-Amz-Expires=300&X-Amz-Signature=4f81c8d9c5f80a2d31b58c426bd15493d7524bba73b3e616adb425c5799b33aa&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=mesa-zink_22.0.5-5_aarch64.deb&response-content-type=application/octet-stream  401                     E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/41365b00-c4e4-4bcf-af5f-772821c08142?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240913/us-east-1/s3/aws4_request&X-Amz-Date=20240913T050547Z&X-Amz-Expires=300&X-Amz-Signature=4c6f74f6801a8413bce70803125d85e0aaff966837cda03c5d35ea9df43a9d02&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=virglrenderer-mesa-zink_20220627_aarch64.deb&response-content-type=application/octet-stream  401
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Expected result

Should install

### Actual result

Throws error

### System details

~ $ uname -a
Linux localhost 4.14.186-perf-gf8d872e9279c #1 SMP PREEMPT Tue Sep 19 12:46:50 UTC 2023 aarch64 Android

**Comment by licy183** [comment]
I can't reproduce it. Seems like your device has connection issues to GitHub Releases.

**Comment by IntinteDAO** [comment]
> The command:
> 
> `~ $ pkg install mesa-zink virglrenderer-mesa-zink vulkan-loader-android`
> 
> Generates this error:
> 
> ```
> E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/fbe2a827-a41b-48d9-bafa-ce6f352a679c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240913/us-east-1/s3/aws4_request&X-Amz-Date=20240913T050547Z&X-Amz-Expires=300&X-Amz-Signature=4f81c8d9c5f80a2d31b58c426bd15493d7524bba73b3e616adb425c5799b33aa&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=mesa-zink_22.0.5-5_aarch64.deb&response-content-type=application/octet-stream  401                     E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/41365b00-c4e4-4bcf-af5f-772821c08142?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240913/us-east-1/s3/aws4_request&X-Amz-Date=20240913T050547Z&X-Amz-Expires=300&X-Amz-Signature=4c6f74f6801a8413bce70803125d85e0aaff966837cda03c5d35ea9df43a9d02&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=virglrenderer-mesa-zink_20220627_aarch64.deb&response-content-type=application/octet-stream  401
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> ### Expected result
> 
> Should install
> ### Actual result
> 
> Throws error
> ### System details
> 
> ~ $ uname -a Linux localhost 4.14.186-perf-gf8d872e9279c #1 SMP PREEMPT Tue Sep 19 12:46:50 UTC 2023 aarch64 Android

And if you have Adreno 6xx and 7xx, you can use Zink on newest mesa, you don't need to downgrade

**Comment by kripper** [comment]
It's not a connection error, but a missing reference. Here are the full logs.

~ $ pkg install virglrenderer-mesa-zink                           Testing the available mirrors:
[*] (10) https://packages-cf.termux.dev/apt/termux-main: ok
[*] (1) https://mirror.textcord.xyz/termux/termux-main: bad
[*] (1) https://mirror.nevacloud.com/applications/termux/termux-main: ok
[*] (1) https://linux.domainesia.com/applications/termux/termux-main: ok
[*] (1) https://mirror.albony.xyz/termux/termux-main: ok
[*] (1) https://mirrors.cbrx.io/apt/termux/termux-main: ok
[*] (1) https://packages.nscdn.top/termux-main: bad
[*] (1) https://mirror.bardia.tech/termux/termux-main: bad
[*] (1) https://mirrors.dgut.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.cqupt.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.aliyun.com/termux/termux-main: ok
[*] (1) https://mirror.iscas.ac.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.njupt.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.sdu.edu.cn/termux/termux-main: ok
[*] (1) https://mirror.nyist.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.sau.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.pku.edu.cn/termux/termux-main/: ok
[*] (1) https://mirrors.nju.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.bfsu.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.sustech.edu.cn/termux/apt/termux-main: ok
[*] (1) https://mirrors.scau.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.hit.edu.cn/termux/apt/termux-main: bad
[*] (1) https://mirrors.ustc.edu.cn/termux/apt/termux-main: ok
[*] (1) https://packages.termux.dev/apt/termux-main: ok
[*] (1) https://termux.astra.in.ua/apt/termux-main: ok
[*] (1) https://termux.mentality.rip/termux-main: ok
[*] (1) https://termux.librehat.com/apt/termux-main: ok
[*] (1) https://mirrors.sahilister.in/termux/termux-main: ok
[*] (4) https://grimler.se/termux/termux-main: ok
[*] (1) https://mirror.termux.dev/termux-main: bad
[*] (1) https://mirror.accum.se/mirror/termux.dev/termux-main: ok
[*] (1) https://termux.3san.dev/termux/termux-main: ok
[*] (1) https://md.mirrors.hacktegic.com/termux/termux-main: ok
[*] (1) https://mirror.mwt.me/termux/main: ok
[*] (1) https://termux.cdn.lumito.net/termux-main: ok
[*] (1) https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] (1) https://mirrors.utermux.dev/termux/termux-main: ok
[*] (1) https://mirror.fcix.net/termux/termux-main: ok
[*] (1) https://mirror.vern.cc/termux/termux-main: ok
[*] (1) https://dl.kcubeterm.com/termux-main: bad
[*] (1) https://mirror.mwt.me/termux/main: ok
[*] (1) https://mirror.csclub.uwaterloo.ca/termux/termux-main: ok
[*] (1) https://mirrors.wale.id.au/termux/termux-main: bad
[*] (1) http://mirror.mephi.ru/termux/termux-main: ok
[*] (1) https://mirror.surf/termux/termux-main/: ok
Picking mirror: (0) /data/data/com.termux/files/usr/etc/termux/mirrors/default
Hit:2 https://rendiix.github.io android-tools InRelease
Get:1 https://turdl.kcubeterm.com tur-packages InRelease [17.5 kB]
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:5 https://dl.bintray.com/grimler/game-packages-24 games Release
  404  Not Found
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  404  Not Found
Get:7 https://packages-cf.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Get:8 https://packages-cf.termux.dev/apt/termux-x11 x11 InRelease [14.0 kB]
Get:9 https://turdl.kcubeterm.com tur-packages/tur aarch64 Packages [50.8 kB]
Get:10 https://packages-cf.termux.dev/apt/termux-main stable/main ~ $ pkg install virglrenderer-mesa-zink
Checking availability of current mirror:                          [*] https://packages-cf.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree                                          Reading state information... Done
The following packages were automatically installed and are no longer required:
  apr apr-util libopenblas libprotobuf libthread-db libusb          openjpeg-tools
Use 'apt autoremove' to remove them.                              The following additional packages will be installed:
  mesa-zink xorg-xrandr                                           Suggested packages:
  mesa-zink-dev                                                   The following packages will be REMOVED:
  mesa
The following NEW packages will be installed:
  mesa-zink virglrenderer-mesa-zink xorg-xrandr                   0 upgraded, 3 newly installed, 1 to remove and 146 not upgraded.
Need to get 8046 kB/8079 kB of archives.
After this operation, 17.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://tur.kcubeterm.com tur-packages/tur aarch64 mesa-zink aarch64 22.0.5-5
  401                                                             Err:2 https://tur.kcubeterm.com tur-packages/tur aarch64 virglrenderer-mesa-zink aarch64 20220627
  401
E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/fbe2a827-a41b-48d9-bafa-ce6f352a679c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240914/us-east-1/s3/aws4_request&X-Amz-Date=20240914T113041Z&X-Amz-Expires=300&X-Amz-Signature=2d8e18cbe766b70bccc1340ff1dc545b147676ff4f52240bf656822be66be66f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=mesa-zink_22.0.5-5_aarch64.deb&response-content-type=application/octet-stream  401
E: Failed to fetch https://objects.githubusercontent.com/github-production-release-asset-2e65be/509717777/41365b00-c4e4-4bcf-af5f-772821c08142?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction/20240914/us-east-1/s3/aws4_request&X-Amz-Date=20240914T113041Z&X-Amz-Expires=300&X-Amz-Signature=f9bc67355a22e049c475780958f5226d21665cabf7b899b2cc2eb4063bd2439d&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=509717777&response-content-disposition=attachment; filename=virglrenderer-mesa-zink_20220627_aarch64.deb&response-content-type=application/octet-stream  401
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by kripper** [comment]
> And if you have Adreno 6xx and 7xx, you can use Zink on newest mesa, you don't need to downgrade

Can you please provide more details?
Should I try other mesa package that includes zink?
I've been following https://ivonblog.com/en-us/posts/termux-x11/. Maybe it is outdated?

Anyway, I'm more interested in using Vulkan to compute for LLM inference.
Should I better try Venus?
Are there binary Venus packages for my architecture?

**Comment by IntinteDAO** [comment]
> > And if you have Adreno 6xx and 7xx, you can use Zink on newest mesa, you don't need to downgrade
> 
> My GPU is Mali :-(
> 
> Can you please provide more details? Should I try other mesa package that includes zink? I've been following https://ivonblog.com/en-us/posts/termux-x11/. Maybe it is outdated?
> 
> Anyway, I'm more interested in using Vulkan to compute for LLM inference. Should I better try Venus? Are there binary Venus packages for my architecture?

I think you can't use new version of Zink, however you can try
export MESA_LOADER_DRIVER_OVERRIDE=zink
export USE_HEAP=1
export GALLIUM_DRIVER=zink
export VBLANK_MODE=0

<your application>

You can use virgl and it should work without any problems with Mali, but It's slower than Zink

**Comment by kripper** [comment]
Thanks. I will try. Does it also support Vulkan compute for LLM inference?

**Comment by kripper** [comment]
As you correctly mentioned, it was a problem on my env. I fixed it by upgrading all packages.
Zink is working now:

~ $ MESA_LOADER_DRIVER_OVERRIDE=zink GALLIUM_DRIVER=zink ZINK_DESCRIPTORS=lazy glxgears
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G57 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance                                        ZINK: USING LAZY DESCRIPTORS                                      ZINK: warning, this is cpu-based conditional rendering, say bye-bye to fps
