### ISSUE TITLE
[Bug]: Can't install TUR on Termux on Google Play

### ISSUE THREAD

**Issue by Usinganame** [termux-user-repository/tur#1196]
### Problem description

As the title states, there is no `tur-repo` on the termux app, at least on the Play store version (I don't know why they would use a different repo, but they do)

### What steps will reproduce the bug?

* Download Termux from Google play
* Make sure repositories are updated `pkg up`
* Attempt to install tur-repo `pkg in tur-repo`

### What is the expected behavior?

Tur-repo installs

### System information

termux-info:

```
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.08.29
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# x11-repo (sources.list.d/x11.list)
deb https://x11-packages.termux.net/ x11 main
Updatable packages:
openbox/x11 3.6.1-58 aarch64 [upgradable from: 3.6.1-57]
termux-tools version:
3.0.8
Android version:
14
Kernel build information:
Linux localhost 5.4.254-qgki-28582291-abG998USQSCGXH2 #1 SMP PREEMPT Tue Aug 27 10:15:26 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G998U
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
```

**Comment by licy183** [comment]
You should report it to https://github.com/termux-play-store/termux-packages.

**Comment by fornwall** [comment]
It's available now (and @Usinganame reports initial success here: https://github.com/termux-play-store/termux-packages/issues/6#issuecomment-2355714727), so this issue can be closed :tada: .

If there is any issue that looks specific to running a TUR package under the bumped `targetSdk` of Termux on Google Play you can ping me and will look into it!
