### ISSUE TITLE
Create a new repo `termux-user-repository/tur-repology-metadata`

### ISSUE THREAD

**Issue by knyipab** [termux-user-repository/tur#1203]
Any chance TUR could create a repo `tur-repology-metadata` resembling the termux-package one (https://github.com/termux/repology-metadata)? I adapted a working repo at https://github.com/knyipab/tur-repology-metadata and you may just copy those files to `termux-user-repository`. Should be effortless. Thank you!

After that, we can
1. ask repology to add TUR (ref: https://github.com/repology/repology-updater/issues/628), easy provided their existing infrastructure
2. change or patch in TUR for [this line in termux-packages script](https://github.com/termux/termux-packages/blob/403f52483728224407c7c41a13c9a6c3129fe9d8/scripts/updates/api/dump-repology-data#L31-L34) to `inrepo=tur`
3. turn on auto update for some TUR packages even they aren't from gitlab/github

This is indeed a continuation of discussion in #1174

**Comment by licy183** [comment]
Added in https://github.com/termux-user-repository/tur-repology-metadata. Thanks!

**Comment by knyipab** [comment]
Thanks! Repology has added tur: https://repology.org/repository/tur

And I just made a PR #1206 to enable such feature
