### ISSUE TITLE
[Bug]: Package `playit` needs to be updated

### ISSUE THREAD

**Issue by explor4268** [termux-user-repository/tur#1213]
### Problem description

The package `playit` is still at `0.15.11`, which is outdated.
Automatic updates for this package needs to be enabled to ensure continued service.

### What steps will reproduce the bug?

```bash
pkg upgrade
pkg install tur-repo
```
```
~ $ pkg show playit
Package: playit
Version: 0.15.11
Maintainer: @nisheri-ascar
Installed-Size: 3604 kB
Homepage: https://playit.gg
Download-Size: 1373 kB
APT-Sources: https://tur.kcubeterm.com tur-packages/tur aarch64 Packages
Description: playit is a global proxy that allows anyone to host a server without port forwarding.
```
```bash
pkg install playit
```
```
~ $ playit-cli version
0.15.11
```

### What is the expected behavior?

Version is the latest version, at the time of writing this, it is `0.15.23`

### System information

Not relevant

**Comment by licy183** [comment]
Should be closed by https://github.com/termux-user-repository/tur/commit/72bffc77517dcbb13150e9d2fb2dc95eec13dbe1
