### ISSUE TITLE
[Bug]: flang-16 fails to install

### ISSUE THREAD

**Issue by pbnewsom** [termux-user-repository/tur#1259]
### Problem description

The following packages have unmet dependencies:
 flang-16 : Depends: libllvm-16 (= 20220907-1) but 1:16.0.6-1 is to be installed
E: Unable to correct problems, you have held broken packages.

libllvm-16.0.6-1 is installed.
I have unistalled, pkg autoclean, pkg update && pkg upgrade, reinstalled libllvm successfully. same effect.
i have chamged repos. same effect.
same happens with a separate aarch 64, android 14 installation.

### What steps will reproduce the bug?

pkg i flang-16 -y

### What is the expected behavior?

expect flang pkg installed

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=2842
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.niranjan.co/termux-main stable main
# sources.list.d/termux-adb.list
deb https://nohajc.github.io termux extras                 # tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# root-repo (sources.list.d/root.list)
deb https://termux.niranjan.co/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://termux.niranjan.co/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.6
Android version:
12
Kernel build information:
Linux localhost 4.9.227-24348263 #1 SMP PREEMPT Wed May 29 16:36:35 KST 2024 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A025U
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:15
com.termux.styling versionCode:1000
```

**Comment by licy183** [comment]
flang-16 is no more built in this repository. It takes too long to compile it. I could re-enable it later.

**Comment by pbnewsom** [comment]
Thanks for replying. I've search a lot of sites on this topic, but haven't found a current solution.  Without a fortran compiler, termux isn't a viable solution for scientific computing. Thanks.

**Comment by licy183** [comment]
flang has been packaged in Termux main repository. You can install it through `apt install flang`.

**Comment by pbnewsom** [comment]
Thank you.  I just recieved the following messages:
The following packages have unmet dependencies:
 flang-16 : Depends: clang-16 but it is not going to be installed
Depends: lld-16 but it is not going to be installed
Depends: llvm-16 but it is not going to be installed
Depends: mlir-16 but it is not going to be installed
Depends: libllvm-16 (= 20220907-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Attempts to install clang-16 failed due to a connection error so I must wait a few hours.

**Comment by licy183** [comment]
Is there a reason you must use flang-16? If not, I recommend using the latest version of flang (flang-19).

**Comment by pbnewsom** [comment]
when i use the command apt search fortran, the package that comes up is flang-16. I tried to use pkg i flang-19 and got E: unable to locate flang-19

**Comment by licy183** [comment]
flang 19 names `flang`. Run `apt install flang`.

**Comment by pbnewsom** [comment]
I get this:
u0_a241@localhost~  apt install flang
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package flang

**Comment by licy183** [comment]
Ahhh. I don't notice that you're using armv8l Termux. `flang` will not work on 32-bit arches. You could possibly install gcc toolchain from TUR (`pkg install gcc-11`) and it contains `gfortran` as fortran compiler.

**Comment by pbnewsom** [comment]
Installing gcc-11 did install gfortran-11 which I aliased to gfortran.
gfortran --version
GNU Fortran (GCC) 11.5.0

As I now have a fortran compiler, the issue is resolved. Thank you.

I did mention that flang failed to install on a device with an aarch64 CPU architechure.

**Comment by licy183** [comment]
> I did mention that flang failed to install on a device with an aarch64 CPU architechure.

`armv8l` means that you're using an arm32 rootfs, rather than an aarch64 roots.
