### ISSUE TITLE
[BUG] REMOVE Shark

### ISSUE THREAD

**Issue by E343IO** [termux-user-repository/tur#126]
- `Additional packages like 7z packages as : p7zip or p7zip-full`

- **can't be executed while installing package,**

- ***Becoz shark is installing as a package, normal shell commands can be in use,***
- ***remove shark from tur-repo i'll PR for new one. Later on***

> @licy183 if i'm wrong about this, then please explain!

*Thanks for Ur help and support @licy183*

**Comment by E343IO** [comment]
> * `Additional packages like 7z packages as : p7zip or p7zip-full`
> * **can't be executed while installing package,**
> * _**Becoz shark is installing as a package, normal shell commands can be in use,**_
> * _**remove shark from tur-repo i'll PR for new one. Later on**_
> 
> > @licy183 if i'm wrong about this, then please explain!
> 
> _Thanks for Ur help and support @licy183_

***Bro Reply!!!!***

**Comment by licy183** [comment]
Emmm... I think there is no need to remove this package. You could submit a PR and override the `build.sh`.

PS: Removing packages is a little hard for TUR, as the scripts don't provide such a function...

**Comment by E343IO** [comment]
> 

_Well okay. I'LL PR FOR THAT_

**Comment by 2096779623** [comment]
> * Additional packages like 7z packages as : p7zip or p7zip-full

Has been added in [termux-packages](https://github.com/termux/termux-packages/tree/master/packages/p7zip).
