### ISSUE TITLE
[Bug]: Octave-x NOT work

### ISSUE THREAD

**Issue by milen-prg** [termux-user-repository/tur#1270]
### Problem description

https://github.com/termux/termux-packages/issues/21868#issue-2598302903

### What steps will reproduce the bug?

https://github.com/termux/termux-packages/issues/21868#issue-2598302903

### System information

termux-info:

```

```

**Comment by licy183** [comment]
`octave-x` doesn't build with GUI support (Qt). Its configure file doesn't find `qcollectiongenerator` and `qhelpgenerator`.
