### ISSUE TITLE
[Bug]: code oss - quality attribute missing in product.json

### ISSUE THREAD

**Issue by knyipab** [termux-user-repository/tur#1276]
### Problem description

"quality": "stable" is missing in the product.json of code oss, which causes some extension to fail, e.g. Remote - SSH rely on this quality attribute to download corresponding binary for the remote host.  

### What steps will reproduce the bug?

After doing some patches on product.json according to AUR's code-marketplace and code-features, download the extension and try to connect to a host. It will prompt 404 error that cannot download the code server for remote host. That's because the URL contain "quality" is missing and parsed as "undefined" in the URL path. 

### What is the expected behavior?

I think it would be better to replace code-oss/0005-use-open-vsx.org-as-extensions-gallery.patch by the one in Archlinux official repo which provide "quality": "stable". 
https://gitlab.archlinux.org/archlinux/packaging/packages/code/-/blob/main/product_json.diff?ref_type=heads

### System information

Irrelevant

**Comment by licy183** [comment]
I haven't rebuilt `code-oss` these days. There is something wrong with chromium builder, but I don't have enough time to fix it...

**Comment by licy183** [comment]
Emmm... The last time I built `code-oss`, I tried 11 times before I finally passed the CI.

![image](https://github.com/user-attachments/assets/8a6197a9-1ef5-4cc8-9100-89bea14c84c2)
