### ISSUE TITLE
Package request

### ISSUE THREAD

**Issue by GH05T-HUNTER5** [termux-user-repository/tur#128]
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
TERMUX_PKG_HOMEPAGE=https://github.com/GH05T-HUNTER5/GH05T-INSTA
TERMUX_PKG_DESCRIPTION="Instagram Account Hacking Total Package for Termux users . safe to use , BruteForce Attack "
TERMUX_PKG_LICENSE=" MIT license"
TERMUX_PKG_MAINTAINER="@termux-user-repository"
TERMUX_PKG_VERSION=2.3.2
TERMUX_PKG_SRCURL=https://github.com/GH05T-HUNTER5/GH05T-INSTA/archive/refs/tags/GH05T-INSTA.3.01.tar.gz
TERMUX_PKG_SHA256=c2b167d7fea616792f6ad2fe970e804815e555d801ab8f2bb19c966ac9c1ca1c
TERMUX_PKG_DEPENDS="wget, curl, php, python "
TERMUX_PKG_PLATFORM_INDEPENDENT=true

SETUP

cd $HOME/GH05T-INSTA/ && python install.py 

Setup "complete"

Just type gh05t
Advanced

**Comment by Arwaarwa3** [comment]
gh05t
