### ISSUE TITLE
[Package]: python-numpy1

### ISSUE THREAD

**Issue by nguynkhn** [termux-user-repository/tur#1282]
### Name

Python Numpy (version 1)

### Source code URL

https://github.com/numpy/numpy

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by licy183** [comment]
`python -m pip install 'numpy<2' --extra-index-url https://termux-user-repository.github.io/pypi/`
