### ISSUE TITLE
Numpy Scipy Version mismatch

### ISSUE THREAD

**Issue by defencedog** [termux-user-repository/tur#141]
Reporting this because terminal asked me to do so

`WARNING: python-scipy is compiled with numpy 1.23.4, but numpy 1.23.4-2 is installed. It seems that python-numpy has been upgraded. Please report it to https://github.com/termux-user-repository/tur if any bug happens.`

**Comment by licy183** [comment]
That's a bug... I will fix it in next scipy release.

**Comment by defencedog** [comment]
@licy183 Also plz tell why I cannot use `python-scipy, python-numpy` with my 3.9?
```
The following packages will be REMOVED:
  python-is-python3.9
The following NEW packages will be installed:
  python python-numpy python-scipy
```

**Comment by licy183** [comment]
This is expected behavior. TUR doesn't provide pre-built numpy and scipy for python3.9. You need to install them manually on your device.
```
MATHLIB=m python3.9 -m pip install numpy scipy
```

**Comment by defencedog** [comment]
Got installed `numpy-1.23.4` without any hassle
`MATHLIB=m python3.9 -m pip install numpy`
`scipy` gave some ninja error did this no hassle & success 
`MATHLIB=m python3.9 -m pip install ninja==1.10.0`

...will report on biggest install archive in a whie

**Comment by licy183** [comment]
`ninja` package from pip will not work on Termux until upstream changes the way to build it. `numpy >= 1.9.0` tries to use `mesonpy` and will mark `ninja` as build dependencies. You could try to install an older version.
```
MATHLIB=m python3.9 -m pip install 'scipy<1.9.0'
```

**Comment by defencedog** [comment]
@licy183 which this chemical engineer would have seen your erfect reply before wasting an hour...
You're correct versions are very important, this worked
```
pkg i python-is-python3.9
pkg remove ninja
pkg i re2c
MATHLIB=m python3.9 -m pip install ninja==1.10.0
MATHLIB=m python3.9 -m pip install scipy==1.8.0
```
`ninja` was installed by pkg `1.11.1` but it was not being picked up by `pip`

All Ok for me
