### ISSUE TITLE
[Bug]: vkmark package duplication

### ISSUE THREAD

**Issue by Maxython** [termux-user-repository/tur#1411]
### Problem description

There was a problem compiling the ollama package due to duplication of the vkmark package (`tur/vkmark` with `packages/vkmark`). The vkmark package was recently added to the termux-packages repository - https://github.com/termux/termux-packages/commit/e7c7b3c5ee7624d4076bd16e49e376bfb4b5dc7c

### What steps will reproduce the bug?

https://github.com/termux-pacman/tur/issues/10

### What is the expected behavior?

Removing or renaming the vkmark package to resolve the conflict

### System information

Everywhere

**Comment by licy183** [comment]
Already fixed by https://github.com/termux-user-repository/tur/commit/0321a40c2185a7260a6ef8055cd362a2610b6f26.
