### ISSUE TITLE
Relase files have incorrect syntax

### ISSUE THREAD

**Issue by Neo-Oli** [termux-user-repository/tur#168]
**Describe the bug**
The format of the Release files are slightly wrong.

https://github.com/termux-user-repository/dists/blob/860ff401a1ace3271bd731f9e4e096468ef438e2/dists/tur-packages/InRelease#L10

The `Components` value must not be quoted.

https://wiki.debian.org/DebianRepository/Format#Components

It causes tools like aptly to fail as it will try to download files with the spare `"` in the URL.
For Example:
https://tur.kcubeterm.com/dists/tur-packages/%22tur/binary-aarch64/Packages

**To Reproduce**
```
aptly mirror create tur https://tur.kcubeterm.com tur-packages;aptly mirror update tur
```
This will lead to a bunch of 404 errors.

**Comment by licy183** [comment]
Should fixed in https://github.com/termux-user-repository/dists/commit/0d83a567b2b4d0e10f35bfd96aa79403390f82ab. Thanks for your report!
