### ISSUE TITLE
[Question] :Can we sumbit packages related to hacking?

### ISSUE THREAD

**Issue by T-Dynamos** [termux-user-repository/tur#18]
Eg: thc-hydra

**Comment by kcubeterm** [comment]
oo. I am bit reluctant when comes to hacking packages. The reason behind it is. people starts flooding in termux community. This is the main reason to remove hacking packages form official repository. 

But anyway. go ahead. This is User repository. Will add warning to not discuss any TUR packages in Official Termux community.

**Comment by T-Dynamos** [comment]
> oo. I am bit reluctant when comes to hacking packages. The reason behind it is. people starts flooding in termux community. This is the main reason to remove hacking packages form official repository.
> 
> But anyway. go ahead. This is User repository. Will add warning to not discuss any TUR packages in Official Termux community.

But suppose if there's an issue related to pip3 kivy compilation user can recommend tur?

**Comment by kcubeterm** [comment]
Any TUR package related issues should be discussed in TUR forum (Github Discussion) rather than Termux forum.
