### ISSUE TITLE
Package request: mitmproxy_wireguard

### ISSUE THREAD

**Issue by SunPodder** [termux-user-repository/tur#191]
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name: mitmproxy_wireguard
Homepage: https://github.com/decathorpe/mitmproxy_wireguard
Source link: https://github.com/decathorpe/mitmproxy_wireguard

**Additional Info:**

**Comment by licy183** [comment]
Although I don't know whether it will work on Termux or not, this package itself will be able to provide...
