### ISSUE TITLE
Package request: PHP 7

### ISSUE THREAD

**Issue by Dichvucoder** [termux-user-repository/tur#193]
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name: php 7.4.33
Homepage: https://php.net/
Source link: https://windows.php.net/downloads/releases/php-7.4.33-src.zip

**Additional Info:**

**Comment by licy183** [comment]
This is a little hard to compile because php7 depends on `openssl-1.1` rather than `openssl-3`. We probably need to provide a branch of libraries to satisfy its dependencies...
