### ISSUE TITLE
Error while building `python-pillow`

### ISSUE THREAD

**Issue by T-Dynamos** [termux-user-repository/tur#20]
Error
```
ERROR: Cannot find _sysconfigdata*.py. Looked in /data/data/com.termux/files/usr/lib/python3.9, /data/data/com.termux/files/usr/lib/python3.9/*
```
[Build log](https://pipelines.actions.githubusercontent.com/serviceHosts/a336c158-faf4-418c-b409-8e034780e4f3/_apis/pipelines/1/runs/13/signedlogcontent/5?urlExpires=2022-07-05T15%3A26%3A31.8470380Z&urlSigningMethod=HMACV1&urlSignature=cPq9upCemjIaXXRmhI0DbXJ%2FyHRqd5k6kEFUowfxkBc%3D)
[build.sh file](https://github.com/T-Dynamos/tur/blob/master/tur/python-pillow/build.sh)

**Comment by kcubeterm** [comment]
Log link expire ? 

Why not using `_PYTHON_VERSION=$(. $TERMUX_SCRIPTDIR/packages/python/build.sh; echo $_MAJOR_VERSION)` 

Instead of hardcoding version.

**Comment by kcubeterm** [comment]
BTW, that's nice idea to add those listed packages here.

**Comment by T-Dynamos** [comment]
> Log link expire ?
> 
> Why not using `_PYTHON_VERSION=$(. $TERMUX_SCRIPTDIR/packages/python/build.sh; echo $_MAJOR_VERSION)`
> 
> Instead of hardcoding version.

Gave error of file not found

**Comment by licy183** [comment]
I have just rewritten the `build.sh` and submit a Pull Request. Actually, I think `_PYTHON_VERSION` should be set to `3.10` (the `_MAJOR_VERSION` in `python`'s `build.sh`).
