### ISSUE TITLE
[Discussion]: Setup an apt repo that supports on-device build

### ISSUE THREAD

**Issue by licy183** [termux-user-repository/tur#23]
Lots of packages is not friendly to cross compile, such as `openblas` and `scipy`. Currently, TUR is actually a repo containing `build.sh` which must be able to cross-compile and may be able to compile on device.

Termux has `termux-docker`, and it provides the ability to test packages under a docker environment on host PC. But `clang` under `termux-docker:aarch64/arm` has issues when using binfmt_misc and `qemu-user-aarch64/arm`. It will hang on or crash when compiling with `-std=c++11`. But `self-hosted` runner of `aarch64` can be used to solve this problem.

I have an aarch64 device and can be used as a `self-hosted` runner. And I think it is possible to create such a repo.

Maybe we can add a new source repository called `tur-on-device` under `termux-user-repository`. And one more apt repo should be added.

CC @kcubeterm @2096779623

**Comment by kcubeterm** [comment]
Look good to me.

**Comment by kcubeterm** [comment]
> And one more apt repo should be added.

I don't get it, Why another apt repo ? Can be served via main apt repo.

**Comment by kcubeterm** [comment]
https://github.com/termux-user-repository/tur/blob/7e916c6836ea0ff722fbaf68b98ae4060b96cfe7/.github/workflows/packages.yml#L213

just add this in workflow. rest is done itself by dist script (currently runs in my pc manually).

**Comment by licy183** [comment]
> https://github.com/termux-user-repository/tur/blob/7e916c6836ea0ff722fbaf68b98ae4060b96cfe7/.github/workflows/packages.yml#L213
> 
> just add this in workflow. rest is done itself by dist script (currently runs in my pc manually).

OK, I will add it to tur-on-device's workflow.

**Comment by kcubeterm** [comment]
https://github.com/termux-user-repository/dists/pull/1 

Done.
