### ISSUE TITLE
[Package]: apk-builder

### ISSUE THREAD

**Issue by mishpro-programm** [termux-user-repository/tur#239]
### Name

apk-builder

### Home page URL

https://github.com/mishpro-programm/apk-builder

### Source code URL

https://github.com/mishpro-programm/apk-builder

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by licy183** [comment]
I don't think this package will be added. IMO this is `Few lines of scripting code`.
