### ISSUE TITLE
Bug in Pkg Upgrade ?

### ISSUE THREAD

**Issue by BDhackers009** [termux-user-repository/tur#241]
Zphisher v2.3.5 pr has been merged recently #237

But it still shows version 2.3.2 on pkg list & installs the old version

**Comment by T-Dynamos** [comment]
Add `tur-hacking` in this file `$PREFIX/etc/apt/sources.list.d/tur.list`

**Comment by BDhackers009** [comment]
"gotchu..

**Comment by Alittabell** [comment]
> That's great tho!
