### ISSUE TITLE
[Package]: carbonyl

### ISSUE THREAD

**Issue by T-Dynamos** [termux-user-repository/tur#246]
### Name

carbonyl 

### Home page URL

https://github.com/fathyb/carbonyl

### Source code URL

https://github.com/fathyb/carbonyl

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by licy183** [comment]
I haven't got chromium built sucessfully with rust toolchain enabled, so I think it is quite hard to build.

**Comment by licy183** [comment]
I've built the binary from source on my computer, but it cannot work properly and it shows a blank screen.

![image](https://user-images.githubusercontent.com/45286352/216822695-ded92bdc-0d2b-4754-9a48-1d36484f2f88.png)

**Comment by licy183** [comment]
Closes via #255.
