### ISSUE TITLE
[Package]: python-cryptography

### ISSUE THREAD

**Issue by fatinghenji** [termux-user-repository/tur#269]
### Name

python-cryptography

### Home page URL

cryptography.io

### Source code URL

https://github.com/pyca/cryptography

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

This package is available in the official sources, but requires python 3.11.1 and above. I'm using python 3.8 provided in tur, so I can't install it and request to compile a package that can be installed with python 3.8.

**Comment by licy183** [comment]
Added in termux-user-repository/pypi-index-tur@f73de00e41b9e1b349a8f5292554ebce92ce546b.
Please install it through `python3.8 -m pip install cryptography --extra-url https://termux-user-repository.github.io/pypi`.
