### ISSUE TITLE
[Package]: Mesa-Zink (?)

### ISSUE THREAD

**Issue by IntinteDAO** [termux-user-repository/tur#271]
### Name

Mesa

### Source code URL

https://gitlab.freedesktop.org/mesa/mesa.git

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

I found this tutorial:
https://raw.githubusercontent.com/ThieuMinh26/Proot-Setup/main/Zink

It's about using Zink in Termux, so you've got 3D Acceleration (on Termux-X11). It's not the best option, but maybe we should get it as an alternative for mesa.

I think newest version of Zink require some Vulkan extensions that Android Phone don't support, but this one works (for me at least).

I don't know how to set potential "mesa-zink" as "mesa" alternative that will work for all package, but maybe you know how to set it

**Comment by ThieuMinh26** [comment]
So is it possible for virgl to use android gles driver instead vulkan driver ? i want opengl 3.3 using virgl zink but my vulkan driver didnt fully support it
