### ISSUE TITLE
[Package]: scipy for python3.8

### ISSUE THREAD

**Issue by fatinghenji** [termux-user-repository/tur#275]
### Name

python-scipy

### Home page URL

https://scipy.org/

### Source code URL

https://github.com/scipy/scipy

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

There is a `python-scipy` in the tur library, but a higher version of python is needed, so request a `python-scipy` that will run in python 3.8.Thanks.

**Comment by licy183** [comment]
Close via https://github.com/termux-user-repository/pypi-index-tur/pull/8
