### ISSUE TITLE
[Package]: Python Package playwright

### ISSUE THREAD

**Issue by fatinghenji** [termux-user-repository/tur#278]
### Name

playwright

### Home page URL

https://github.com/Microsoft/playwright-python

### Source code URL

https://github.com/Microsoft/playwright-python

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

I'm getting an error when using `pip install playwright`, I hope there is a playwright that can run in python 3.8 environment
 ```python 
ERROR: No version could be found that matches the playwright requirement (from versions: none) 
ERROR: No matching distribution found for playwright 
```

**Comment by licy183** [comment]
This is quite hard I suppose. `playwright` contains some API wrappers to `playwright`, which is a node-based application. I haven't tried to run playwright.
