### ISSUE TITLE
[Discussion]: Add a GPG key

### ISSUE THREAD

**Issue by licy183** [termux-user-repository/tur#28]
Currently, our repo is using @kcubeterm 's GPG key to sign the `Release` file. Rather than using our own GPG keys, I'd prefer adding a new GPG key that is used to sign the TUR repo only. We are going the sign the repo using Github Action, but I don't think it is safe for us to store our own GPG passphrase to the repo's Action Secret.

/CC @kcubeterm @2096779623 @T-Dynamos

**Comment by 2096779623** [comment]
Add a dedicated GPG public key like in [termux-packages](https://github.com/termux/termux-packages/blob/master/packages/termux-keyring/termux-autobuilds.gpg).

**Comment by kcubeterm** [comment]
We are going to sign repo in github action. And it is safe if github secret is safe enough. I just have to create a workflow and all done


Is it nice idea to add our key in termux-keyring for an unofficial apt repo ?

**Comment by kcubeterm** [comment]
> No, We can create a package(e.g tur-keyring). 

Its seems fine. Let's be lazy and add it on termux-keyring. Aren't we a trusted guy :)

**Comment by 2096779623** [comment]
> > No, We can create a package(e.g tur-keyring).
> 
> Its seems fine. Let's be lazy and add it on termux-keyring. Aren't we a trusted guy :)

Well its-pointless was added long ago :)

**Comment by kcubeterm** [comment]
No, idea, why he didn't do. But let's try. What's other member think about it

**Comment by licy183** [comment]
> We are going to sign repo in github action. And it is safe if github secret is safe enough.

Actually, I don't think Github Action Secret is safe enough to store our own GPG key's passphrase. So I think we need to generate another GPG key for the usage of TUR Github Action only. And adding the generated GPG key of TUR Github Action to `termux-keyring` is not a good idea. `termux-keyring` should only contain the GPG keys of termux official repositories.

> No, We can create a package(e.g `tur-keyring`).

I'd prefer this solution. We could create packages named `tur-keyring` and `tur-repo` in `tur` repository, and provide a script to help users download these packages and install them.

**Comment by kcubeterm** [comment]
Nice!!

**Comment by kcubeterm** [comment]
Just create one repo, tur-repo 
That will setup all the requirements when someone install it via apt.

**Comment by licy183** [comment]
TUR uses the same building scripts of current termux packages, so the packages in TUR will not support Android 5/6.

**Comment by kcubeterm** [comment]
added a gpg key at organisations level in github secrets.

**Comment by kcubeterm** [comment]
pub key can be found https://github.com/termux-user-repository/dists/blob/contents/dists/tur-packages/Release.gpg

**Comment by kcubeterm** [comment]
i assigned myself for the following task. 
- [ ]  Adding `tur-repo` in termux as package. 
- [ ]  configuting github ci for signing release files.

**Comment by kcubeterm** [comment]
https://github.com/termux-user-repository/dists/blob/master/.github/workflows/auto_build.yml

github ci configured for signing the release file. this issue should be close.

**Comment by Mati882023** [comment]
> Obecnie nasze repozytorium korzysta z@kcubetermKlucz GPG do podpisania `Release`pliku. Zamiast używać własnych kluczy GPG, wolałbym dodać nowy klucz GPG, który jest używany tylko do podpisywania repozytorium TUR. Podpiszemy repozytorium za pomocą Github Action, ale nie sądzę, żebyśmy mogli bezpiecznie przechowywać własne hasło GPG w tajnym kluczu Action repozytorium.
> 
> /DW@kcubeterm @2096779623 @T-Dynamos
