### ISSUE TITLE
Issues of duplicate packages in current build system. 

### ISSUE THREAD

**Issue by kcubeterm** [termux-user-repository/tur#29]
**Issues 1**: Two packages with same name can't be exist. Suppose we want to add zlib in TUR. Since zlib exist in termux packages already, Buildorder.py will report duplicate package and exit. 

**Workaround 1**: Name package after version. Like zlib1 or zlib1.3 

**Workaround 2**: add ability in setup_environment that could remove those packages from Termux packages directory which has same name in tur dir.

**Issue 2**: Suppose we added a package Holla_worldo and after sometimes Termux also added same package then again buildorder.py reports issues, Here workaround 2 could save us.

**Comment by licy183** [comment]
I think we could rename or remove these packages from TUR when termux main has already have those packages. Having duplicated names between apt repos doen't seem a good solution.

**Comment by kcubeterm** [comment]
Renaming package name seems nice idea. Suppose the packages added in termux repo is older version or newer. But tur needs that specific version of package(others package depends on it)
