### ISSUE TITLE
[Package]: 123elf  

### ISSUE THREAD

**Issue by tuimania** [termux-user-repository/tur#292]
### Name

lotus 1-2-3

### Home page URL

https://lock.cmpxchg8b.com/linux123.html

### Source code URL

https://github.com/taviso/123elf  

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

A native port of Lotus 1-2-3 to Linux. 

The legal status of this program is abandoned program (the company was bought by ibm in the 90's and its products have been discontinued). It's more of a curiosity than anything else... It was very popular in the 80's and early 90's. We have sc-im as a smaller and less complex alternative. I really don't have the patience to read the lotus 1-2-3 manual pages

**Comment by licy183** [comment]
It is just for i386 architecture, so only a little Android devices are able to run this program. Packaging it should be okay to me, but I really don't think that this package is useful...

**Comment by licy183** [comment]
I don't think this package can be added for Android. It is for x86 only, but actually lots of Android devices is arm.
