### ISSUE TITLE
[Package]: wpunix

### ISSUE THREAD

**Issue by tuimania** [termux-user-repository/tur#293]
### Name

WordPerfect

### Source code URL

https://github.com/taviso/wpunix

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

WordPerfect for UNIX Character Terminals  

Another digital scrap similar to the previous one. I have a hunch that in termux there would be legal and portability issues with regards to glibc.

**Comment by licy183** [comment]
Same as #292

**Comment by licy183** [comment]
It also only supports x86...
