### ISSUE TITLE
[Package]: python-grpcio

### ISSUE THREAD

**Issue by qiangz63** [termux-user-repository/tur#309]
### Name

grpcio

### Source code URL

https://pypi.org/project/grpcio/#files

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

Officially provided grpc,but not for python-grpcio.

**Comment by qiangz63** [comment]
After this work,we can install Tensorboard on Termux！

**Comment by nacho00112** [comment]
It seems that grpcio developers now supports termux, there's an installable armv7l prebuilt wheel on PyPI, i guess this can be closed now

**Comment by qiangz63** [comment]
The armv7l version not work on termux, I get the error:
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/data/data/com.termux/files/usr/lib/python3.11/site-packages/grpc/_cython/__init__.py)
