### ISSUE TITLE
Package request: DJGPP

### ISSUE THREAD

**Issue by leap0x7b** [termux-user-repository/tur#344]
### Name

DJGPP

### Home page URL

http://delorie.com/djgpp

### Source code URL

https://delorie.com/bin/cvsweb.cgi/djgpp/

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by IntinteDAO** [comment]
> DJGPP

@leap0x7b 

I think it's libs for MS-DOS and Windows, isn't it?

**Comment by leap0x7b** [comment]
Yeah

**Comment by IntinteDAO** [comment]
> Yeah

So why do you want it on Termux? :P

**Comment by leap0x7b** [comment]
I wanted to make DOS apps on Termux

**Comment by IntinteDAO** [comment]
> I wanted to make DOS apps on Termux

I may be wrong, but the DJGPP is an MS-DOS application. Termux runs Linux applications. If you want to build an MS-DOS application then I guess you should write it in DosBox / DosBox-X and upload DJGPP there.

I could be wrong as I haven't used DJGPP, but from what I remember it's a toolchain for MS-DOS / Windows, not Linux.

**Comment by leap0x7b** [comment]
I know

**Comment by licy183** [comment]
I don't think that DJGPP can be run on Linux platform, so I'll close this package request. I'll reopen it if DJGPP is able to execuate on Linux platform.
