### ISSUE TITLE
[Bug]: python-future build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux-user-repository/tur#350]
### Problem description

[python-future.txt](https://github.com/termux-user-repository/tur/files/11165605/python-future.txt)

2023-04-06T01:56:09.8420188Z /home/builder/termux-packages/tur/python-future/build.sh: line 15: termux_setup_python_crossenv: command not found

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by T-Dynamos** [comment]
Remove `termux_step_pre_configure` function and add `TERMUX_PKG_PYTHON_BUILD_DEPS="wheel"` (this line is used to install packages, which were installed with build-pip previously)
