### ISSUE TITLE
[Package Help]: Dave Gnukem

### ISSUE THREAD

**Issue by IntinteDAO** [termux-user-repository/tur#352]
### Name

Dave Gnukem

### Home page URL

https://djoffe.com/gnukem/

### Source code URL

https://github.com/davidjoffe/dave_gnukem

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

Well - I wanted to move the Dave Gnukem application to Termux. On my phone compiled by hand it works very well. So I started preparing a script that would compile it in the build environment on Termux. The code also compiled correctly, but it doesn't find the libSDL2 library, which is on the system. I have no idea where this problem is coming from.

Of course if anyone has ideas on how to improve the build process, I'm always keen to hear good advice as I'm no expert.

build.sh:
https://paste.hostux.net/?3bc6f627818f25a8#48SFnEBxY7pvh7ysfMp4JPPCMvNPmzyYzboAWuZ5VoK1

```
~ davegnukem
CANNOT LINK EXECUTABLE "davegnukem": library "libSDL2-2.0.so" not found: needed by main executable
```

**Comment by T-Dynamos** [comment]
Add this patch:
```patch
--- dave_gnukem/Makefile        2023-04-09 09:28:18.140092862 +0530
+++ dave_gnukem.mod/Makefile    2023-04-09 09:29:22.770092837 +0530
@@ -21,7 +21,7 @@
 VERSION  = v$(V_NUM) - $(V_DATE)

 # paths
-PREFIX   = /usr/local
+PREFIX   = @TERMUX_PREFIX@
 BIN_DIR  = $(PREFIX)/games
 DATA_DIR = $(PREFIX)/share/games/$(BIN)/# the trailing slash is required for paths in the source
```
Also add:
```bash
TERMUX_PKG_GROUPS="games"
```
Else build script LGTM, Ready for a PR.

**Comment by IntinteDAO** [comment]
> Add this patch:
> 
> ```diff
> --- dave_gnukem/Makefile        2023-04-09 09:28:18.140092862 +0530
> +++ dave_gnukem.mod/Makefile    2023-04-09 09:29:22.770092837 +0530
> @@ -21,7 +21,7 @@
>  VERSION  = v$(V_NUM) - $(V_DATE)
> 
>  # paths
> -PREFIX   = /usr/local
> +PREFIX   = @TERMUX_PREFIX@
>  BIN_DIR  = $(PREFIX)/games
>  DATA_DIR = $(PREFIX)/share/games/$(BIN)/# the trailing slash is required for paths in the source
> ```
> 
> Also add:
> 
> ```shell
> TERMUX_PKG_GROUPS="games"
> ```
> 
> Else build script LGTM, Ready for a PR.

Your fix didn't work, but I made my own based on yours. On the other hand build.sh modified it

On the other hand, the problem still exists - it can't load the library that is in the system. This is strange for me.

**Comment by T-Dynamos** [comment]
I don't know why doesn't works on your device.
![Screenshot_20230409-173125_VNC Viewer](https://user-images.githubusercontent.com/68729523/230771371-f5016e9b-24d3-4614-a522-beddd2b375fe.png)

**Comment by IntinteDAO** [comment]
I sent a request on Discord Termuks to test the package. If no one can be found I'll upload it.

From what I've looked in strace, the application doesn't reference the /data/data/com.termux/files/usr/lib directory to load the library. Very strange.

It's possible that my Termux instance is heavily used and therefore not working.

My question is, does the game start you up straight away or do you have to specify -datadir?

**Comment by T-Dynamos** [comment]
Just ran with no args.

**Comment by licy183** [comment]
> From what I've looked in strace, the application doesn't reference the /data/data/com.termux/files/usr/lib directory to load the library. Very strange.

IMO the reason is that the RPATH of the binary file isn't set correctly. Try to override the LDFLAGS with `-Wl,-rpath=$TERMUX_PREFIX/lib`.

**Comment by licy183** [comment]
Anyway, please test this PR https://github.com/termux-user-repository/tur/pull/355.
