### ISSUE TITLE
[Bug]: chomium not playing audio

### ISSUE THREAD

**Issue by johndebia2022** [termux-user-repository/tur#354]
### Problem description

https://askubuntu.com/questions/284202/chromium-doesnt-play-sound

### What steps will reproduce the bug?

open youtube video on chromium, no sound!

### System information

termux-info:

```

```

**Comment by licy183** [comment]
Have you tried pulseaudio? IIRC chromium used to work with chromium.

**Comment by johndebia2022** [comment]
No it did not work with `pulseaudio`. while firefox is playing fine

**Comment by 2096779623** [comment]
On my device, chromium+pulseaudio works fine.

**Comment by licy183** [comment]
I can confirm that chromium can play sound on my device too.

**Comment by johndebia2022** [comment]
<img width="960" alt="1" src="https://user-images.githubusercontent.com/107757728/231206558-9725d31f-4656-443c-916b-f96be9f97f10.png">

**Comment by licy183** [comment]
I don't know how this panel works. But `chromium` itself can play sound.
In one session start pulseaudio.
```
pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
```

In another session start chromium.
```
DISPLAY=:1 chromium-browser
```

**Comment by johndebia2022** [comment]
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=19226
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.cbrx.io/apt/termux/termux-main stable main
# sources.list.d/termux-desktop-xfce.list
deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras
# root-repo (sources.list.d/root.list)
deb https://mirrors.cbrx.io/apt/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.cbrx.io/apt/termux/termux-x11 x11 main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# sources.list.d/holehan.list
deb https://termux.holehan.org/ termux extras
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
13
Kernel build information:
Linux localhost 4.19.87-25884893 #1 SMP PREEMPT Mon Jan 30 18:52:18 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G986B
LD Variables:
LD_LIBRARY_PATH=/data/data/com.termux/files/home/.local/lib:
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by licy183** [comment]
I cannot reproduce it on my Android 7, Android 9 and Android 12 device...

**Comment by nacho00112** [comment]
May be a problem with your VNC viewer
