### ISSUE TITLE
gcc-default incorrectly installed

### ISSUE THREAD

**Issue by Sertonix** [termux-user-repository/tur#359]
I installed `gcc-default` in termux with pacman and got this error message:

```
(7/8) installing gcc-default-11                    100%
/data/data/com.termux/files/usr/tmp/alpm_4Ectaq/.INSTALL: line 5: dpkg: command not found
error: command failed to execute correctly
(8/8) installing gcc-default                       100%
```

The installation seems to assume the command dpkg is definey but when using pacman it is not. Another problem is that the package is shown as succesfully installed even though it was not.

**Comment by licy183** [comment]
I don't use pacman so I don't know how to fix it.
CC: @Maxython
