### ISSUE TITLE
Auto updating

### ISSUE THREAD

**Issue by IntinteDAO** [termux-user-repository/tur#390]
### Problem description

Sorry to write here, but I could not find such information on Wiki (but maybe I am blind).

Well, some packages have the Auto update option enabled. Potentially very cool it seems, but how it is created generally. What are the requirements for CI/CD to download the latest version, does it download Release or from Git and so on and so forth. I would just like the packages to update themselves and not have to think about it too much.

Cool if there is a manual for TUR and Termux. Although I suspect the mechanism is the same.

### What steps will reproduce the bug?

x

### System information

x

**Comment by licy183** [comment]
Auto-updating is triggered via GitHub Action. It will run `termux_pkg_auto_update` and check if there is any updates for a package. See https://github.com/termux/termux-packages/blob/master/scripts/updates/termux_pkg_auto_update.sh.
