### ISSUE TITLE
[Bug]: code-server treated as web-only, can't install extensions

### ISSUE THREAD

**Issue by jonaskuske** [termux-user-repository/tur#399]
### Problem description

When trying to install language packs or other extensions, it fails with an error, stating that installing extensions is not supported in code-server for Web:

```
Installing extensions...
Installing extension 'ms-ceintl.vscode-language-pack-de'... The 'ms-ceintl.vscode-language-pack-de' extension is not available in code-server for Web.
Failed Installing Extensions: ms-ceintl.vscode-language-pack-de
```

I'm not sure if this is an error with code-server itself or with the installation done through tur-repo, which is why I'm filing the bug here, too. Also, `code-server --version` returns 0.0.0, not sure if that's right. More info here: https://github.com/coder/code-server/issues/6168

### What steps will reproduce the bug?

```
pkg i tur-repo
pkg i code-server
code-server --install-extension ms-ceintl.vscode-language-pack-de
```

### What is the expected behavior?

Extension installs

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16153
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
12
Kernel build information:
Linux localhost 4.14.190-duo-p-0_0_0+ #1 SMP PREEMPT Wed Feb 22 13:31:09 UTC 2023 aarch64 Android
Device manufacturer:
Microsoft
Device model:
Surface Duo
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by licy183** [comment]
I think this is the intended behaviour. The `nodejs` binary `code-server` uses is targeting Android not Linux, and the extensions which labels their platforms as `linux-arm64` are actually for gnu libc, not bionic libc, so they can't work properly. IMO this issue will not be fixed until vscode supports custom platform labels.

**Comment by jonaskuske** [comment]
Yeah, makes sense that extensions requiring linux-arm64 (or any linux/mac/windows platform for that sake) can't be installed on Android. The odd thing was that even extensions targeting the web runtime didn't work. But that's working now since the latest release (`code-server - - version` now properly reports the installed version, too). The only thing still causing issues is installing language packs, but I'm fairly sure this has to do with the code-server specific locale implementation, not with the deployment on tur :)
