### ISSUE TITLE
[Bug]: ValueError: Buffer dtype mismatch, expected 'intp_t' but got 'long long'

### ISSUE THREAD

**Issue by Jonaben1** [termux-user-repository/tur#402]
### Problem description

I installed the TUR repo. Then I installed python-pandas. The installation went successfully (Pandas Version 1.5.3).
However, when I loaded a simple DataFrame, I got a ValueError:

ValueError: Buffer dtype mismatch, expected 'intp_t' but got 'long long'

Here are the logs:

--------
ValueErrorTraceback (most recent call last)
File /data/data/com.termux/files/usr/lib/python3.11/site-packages/IPython/core/formatters.py:708, in PlainTextFormatter.__call__(self, obj)
    701 stream = StringIO()
    702 printer = pretty.RepresentationPrinter(stream, self.verbose,
    703     self.max_width, self.newline,
    704     max_seq_length=self.max_seq_length,
    705     singleton_pprinters=self.singleton_printers,
    706     type_pprinters=self.type_printers,
    707     deferred_pprinters=self.deferred_printers)
--> 708 printer.pretty(obj)
    709 printer.flush()
    710 return stream.getvalue()

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/core/frame.py:1064, in DataFrame.__repr__(self)
   1061     return buf.getvalue()
   1063 repr_params = fmt.get_dataframe_repr_params()
-> 1064 return self.to_string(**repr_params)

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/core/frame.py:1245, in DataFrame.to_string(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, max_rows, max_cols, show_dimensions, decimal, line_width, min_rows, max_colwidth, encoding)
   1226 with option_context("display.max_colwidth", max_colwidth):
   1227     formatter = fmt.DataFrameFormatter(
   1228         self,
   1229         columns=columns,
   (...)
   1243         decimal=decimal,
   1244     )
-> 1245     return fmt.DataFrameRenderer(formatter).to_string(
   1246         buf=buf,
   1247         encoding=encoding,
   1248         line_width=line_width,
   1249     )

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/io/formats/format.py:1136, in DataFrameRenderer.to_string(self, buf, encoding, line_width)
   1133 from pandas.io.formats.string import StringFormatter
   1135 string_formatter = StringFormatter(self.fmt, line_width=line_width)
-> 1136 string = string_formatter.to_string()
   1137 return save_to_buffer(string, buf=buf, encoding=encoding)

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/io/formats/string.py:30, in StringFormatter.to_string(self)
     29 def to_string(self) -> str:
---> 30     text = self._get_string_representation()
     31     if self.fmt.should_show_dimensions:
     32         text = "".join([text, self.fmt.dimensions_info])

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/io/formats/string.py:45, in StringFormatter._get_string_representation(self)
     42 if self.fmt.frame.empty:
     43     return self._empty_info_line
---> 45 strcols = self._get_strcols()
     47 if self.line_width is None:
     48     # no need to wrap around just print the whole frame
     49     return self.adj.adjoin(1, *strcols)

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/io/formats/string.py:36, in StringFormatter._get_strcols(self)
     35 def _get_strcols(self) -> list[list[str]]:
---> 36     strcols = self.fmt.get_strcols()
     37     if self.fmt.is_truncated:
     38         strcols = self._insert_dot_separators(strcols)

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/io/formats/format.py:617, in DataFrameFormatter.get_strcols(self)
    613 def get_strcols(self) -> list[list[str]]:
    614     """
    615     Render a DataFrame to a list of columns (as lists of strings).
    616     """
--> 617     strcols = self._get_strcols_without_index()
    619     if self.index:
    620         str_index = self._get_formatted_index(self.tr_frame)

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/io/formats/format.py:872, in DataFrameFormatter._get_strcols_without_index(self)
    870     str_columns = [[label] for label in self.header]
    871 else:
--> 872     str_columns = self._get_formatted_column_labels(self.tr_frame)
    874 if self.show_row_idx_names:
    875     for x in str_columns:

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/io/formats/format.py:951, in DataFrameFormatter._get_formatted_column_labels(self, frame)
    949 else:
    950     fmt_columns = columns.format()
--> 951     dtypes = self.frame.dtypes
    952     need_leadsp = dict(zip(fmt_columns, map(is_numeric_dtype, dtypes)))
    953     str_columns = [
    954         [" " + x if not self._get_formatter(i) and need_leadsp[x] else x]
    955         for i, x in enumerate(fmt_columns)
    956     ]

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/core/generic.py:6073, in NDFrame.dtypes(self)
   6045 @property
   6046 def dtypes(self):
   6047     """
   6048     Return the dtypes in the DataFrame.
   6049
   (...)
   6071     dtype: object
   6072     """
-> 6073     data = self._mgr.get_dtypes()
   6074     return self._constructor_sliced(data, index=self._info_axis, dtype=np.object_)

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/core/internals/managers.py:273, in BaseBlockManager.get_dtypes(self)
    271 def get_dtypes(self):
    272     dtypes = np.array([blk.dtype for blk in self.blocks])
--> 273     return dtypes.take(self.blknos)

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/core/internals/managers.py:184, in BaseBlockManager.blknos(self)
    174 """
    175 Suppose we want to find the array corresponding to our i'th column.
    176
   (...)
    180 self.blocks[self.blknos[i]]
    181 """
    182 if self._blknos is None:
    183     # Note: these can be altered by other BlockManager methods.
--> 184     self._rebuild_blknos_and_blklocs()
    186 return self._blknos

File /data/data/com.termux/files/usr/lib/python3.11/site-packages/pandas/_libs/internals.pyx:717, in pandas._libs.internals.BlockManager._rebuild_blknos_and_blklocs()

ValueError: Buffer dtype mismatch, expected 'intp_t' but got 'long long'

The same error message is displayed when I tried to read a CSV file.

### What steps will reproduce the bug?

In [1] import pandas as pd

In [2]: df = pd.DataFrame({'Name': ['Ad
   ...: a', 'Obi', 'John', 'Emma'], 'Ge
   ...: nder': ['F', 'M', 'M', 'F'], 'A
   ...: ge': [12, 15, 14, 16]})

In [3]: df

### What is the expected behavior?

DataFrame is supposed to load successfully and a table displayed.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6990
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
9
Kernel build information:
Linux localhost 4.4.147 #1 SMP PREEMPT Wed Jan 12 20:08:29 +08 2022 armv7l Android
Device manufacturer:
ITEL MOBILE LIMITED
Device model:
itel W6004
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by djd1226** [comment]
I ran into the same issue！
termux 0.118
pandas 1.5.3

**Comment by licy183** [comment]
I cannot reproduce it on my x86_64/aarch64 environment. I'll try on arm later.

**Comment by Jonaben1** [comment]
I need help on that please. All libraries installed - python-numpy, python-scipy, even scikit-learn - are all working except python-pandas.

I even tried  installing using pip
'MATHLIB="m" pip3 install pandas'
but to no avail.

I need help pls

**Comment by djd1226** [comment]
> I need help on that please. All libraries installed - python-numpy, python-scipy, even scikit-learn - are all working except python-pandas.
> 
> I even tried installing using pip 'MATHLIB="m" pip3 install pandas' but to no avail.
> 
> I need help pls

The problem is solved，thanks a lot!

**Comment by licy183** [comment]
The latest version of python-pandas has fixed this issue.

**Comment by Jonaben1** [comment]
@licy183  How do i get the latest version as only v1.53 is found

**Comment by licy183** [comment]
apt update && apt install python-pandas

**Comment by Jonaben1** [comment]
thanks a lot @licy183

**Comment by Jonaben1** [comment]
@licy183 Thanks once again. The problem is solved, and issue closed already. I can now perform Machine Learning on Termux. Finally!!
