### ISSUE TITLE
[Bug]: where is mongodb conf location

### ISSUE THREAD

**Issue by altmangood** [termux-user-repository/tur#428]
### Problem description

-

### What steps will reproduce the bug?

after install mongodb, it listen on 127.0.0.1 default。

I want to change the conf file to modify server host and port.

### What is the expected behavior?

-

### System information

termux-info:

```
ZeroTermux
```

**Comment by licy183** [comment]
IIRC `mongod` can start with argument `--config`.

**Comment by altmangood** [comment]
Thanks.this command is also helpful.  > mongod --help
