### ISSUE TITLE
[Bug]: install playwright failed, caused by the greenlet 2.0.1

### ISSUE THREAD

**Issue by minatoAI** [termux-user-repository/tur#436]
### Problem description

when installing playwright and building wheels for greenlet, an error arise.  
i tried installing greenlet 2.0.1, and the error same.

### What steps will reproduce the bug?

1. python -m pip install playwright --extra-index-url https://termux-user-repository.github.io/pypi/
2. Building wheel for greenlet (setup.py) ... error

### What is the expected behavior?

use greenlet 2.0.2, not 2.0.1

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~sONumXe6WcKTClqtZt-N0A==/com.termux-2Ddxiv6OjpzviJWtpCdulA==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=2765
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c43,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c43,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10299
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+9b274f9
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+9b274f9
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
13
Kernel build information:
Linux localhost 4.4.302-perf+ #1 SMP PREEMPT Tue Apr 4 03:55:08 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
MI 5
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by licy183** [comment]
What's your python version? TUR's PyPI doesn't provide a prebuilt version of playwright for the main python version(python 3.11).

**Comment by licy183** [comment]
Try `CFLAGS="-Wno-error=register" python -m pip install playwright --extra-index-url https://termux-user-repository.github.io/pypi/`. Anyway, I'll update the whl to the latest version.

**Comment by licy183** [comment]
Should be fixed by https://github.com/termux-user-repository/pypi/commit/5c2e4b9fe060af4bd29768c9687897f472959e95.

**Comment by minatoAI** [comment]
> Try `CFLAGS="-Wno-error=register" python -m pip install playwright --extra-index-url https://termux-user-repository.github.io/pypi/`. Anyway, I'll update the whl to the latest version.

this command works, many thanks!
Thanks again for your work and help.
