### ISSUE TITLE
[Package]: smartdns

### ISSUE THREAD

**Issue by fatinghenji** [termux-user-repository/tur#446]
### Name

smartdns

### Home page URL

https://pymumu.github.io/smartdns/

### Source code URL

https://github.com/pymumu/smartdns

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

https://github.com/pymumu/smartdns/issues/1218

https://github.com/x4455/smartdns-Android/

**Comment by fatinghenji** [comment]
What is the location of the configuration file `smartdns.conf`?

**Comment by licy183** [comment]
`/data/data/com.termux/files/usr/etc/smartdns/smartdns.conf`



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 12, 2023 00:24 AM
To: ***@***.***&gt;;
Cc: "Uchiha ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [termux-user-repository/tur] [Package]: smartdns (Issue #446)




 
What is the location of the configuration file smartdns.conf?

**Comment by fatinghenji** [comment]
Some problems were encountered：
1. First write the configuration file
```
bind [::]:53 -no-rule-ipset
bind-tcp [::]:53 -no-rule-ipset
server 9.9.9.10 -group bootstrap -exclude-default-group
server 208.67.220.220 -group bootstrap -exclude-default-group
server 77.88.8.8 -group bootstrap -exclude-default-group
server 2606:4700:4700::1111 -group bootstrap -exclude-default-group
server 117.50.10.10 -blacklist-ip -group China
domain-rules /dns.nextdns.io/ -c tcp:853,ping -n bootstrap
domain-rules /dns.alidns.com/ -c tcp:853,ping -n bootstrap
domain-rules /dot.pub/ -c tcp:853,ping -n bootstrap
server-tls dns.nextdns.io -group China
server-tls dns.alidns.com -blacklist-ip -group China
server-tls dot.pub -whitelist-ip -group China -exclude-default-group
address /telecom.ISP/202.96.209.5
server telecom.ISP -whitelist-ip -group China -exclude-default-group
address /unicom.ISP/210.22.70.3
server unicom.ISP -whitelist-ip -group China -exclude-default-group
address /mobile.ISP/221.131.143.69
server mobile.ISP -whitelist-ip -group China -exclude-default-group
domain-rules /dns.adguard.com/ -c tcp:443,ping -n bootstrap
domain-rules /dns.quad9.net/ -c tcp:443,ping -n bootstrap
domain-rules /dns.cloudflare.com/ -c tcp:443,ping -n bootstrap
server-https https://dns.adguard.com/dns-query -group foreign
server-https https://dns.quad9.net/dns-query -group foreign
server-https https://dns.cloudflare.com/dns-query -group foreign
serve-expired yes
cache-persist yes
prefetch-domain yes
dualstack-ip-selection yes
```
2. Start the service with `smartdns start`
3. Query domain name with `nslookup -querytype=ptr smartdns`
```
Server:         114.114.114.114
Address:        114.114.114.114#53

** server can't find smartdns: NXDOMAIN
```
Can you share the configuration file that you tested successfully?

**Comment by licy183** [comment]
Do you have root permission? It is impossible for Termux binaries to bind ports ranged from 1 to 1024 without root.

I only tested it simply so the default configuration is used.
```
dig @localhost -p 8053 baidu.com
```

**Comment by fatinghenji** [comment]
> Do you have root permission? It is impossible for Termux binaries to bind ports ranged from 1 to 1024 without root.
> 
> I only tested it simply so the default configuration is used.
> 
> ```
> dig @localhost -p 8053 baidu.com
> ```

Ah sorry, I forgot I needed to use root permission

**Comment by fatinghenji** [comment]
```
➜  ~ smartdns stop                   
➜  ~ sudo smartdns start                     
➜  ~ nslookup -querytype=ptr smartdns
Server:         114.114.114.114
Address:        114.114.114.114#53

** server can't find smartdns: NXDOMAIN
```
The problem still seems to exist

**Comment by licy183** [comment]
What do you want to do? Do you want to query from the smartdns server? nslookup will use the default DNS server from $PREFIX/resolve.conf. If you want to query from smartdns, please manually specify server.
```
nslookup -port=53 -querytype=ptr smartdns localhost
```
