### ISSUE TITLE
[Bug]: chromium - CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by johndebia2022** [termux-user-repository/tur#460]
### Problem description

~ $ chromium-browser
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/chromium/chrome": cannot locate symbol "ZN3re23RE27ReplaceEPNSt6_ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKS0_RKNS_11StringPieceE" referenced by "/data/data/com.termux/files/usr/lib/chromium/chrome"...
~ $

### What steps will reproduce the bug?

~ $ chromium-browser

### System information

termux-info:

```
Termux Variables:                                     TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID                            TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=32160
TERMUX_IS_DEBUGGABLE_BUILD=0                          TERMUX_MAIN_PACKAGE_FORMAT=debian                     TERMUX_VERSION=0.118.0                                Packages CPU architecture:                            aarch64                                               Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 4.19.87-26203352 #1 SMP PREEMPT Wed Apr 12 11:25:50 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G986B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.shell_loader versionCode:1
com.termux.api versionCode:51
```

**Comment by johndebia2022** [comment]
also build failed

[logs_49.zip](https://github.com/termux-user-repository/tur/files/11794108/logs_49.zip)

**Comment by lululoid** [comment]
I got the same error too
`CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/chromium/chrome": cannot locate symbol "_ZN3re23RE27ReplaceEPNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKS0_RKNS_11StringPieceE" referenced by "/data/data/com.termux/files/usr/lib/chromium/chrome"...
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.19.157-perf-g85e27949fb09 #1 SMP PREEMPT Wed Jan 11 21:56:20 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
220333QAG
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51`

**Comment by George-Seven** [comment]
I am also getting the same error even on fresh install of Termux.

**Comment by Alexanderortizcuellar** [comment]
I'm having the same error, seems like an update broke one of the dependencies

**Comment by 5A52** [comment]
This happens after last update termux-packages. Unfortunately don't know which one exactly.

**Comment by johndebia2022** [comment]
Thanks to @licy183 I have built the package after comment https://github.com/termux-user-repository/tur/commit/63992ed784c00b2a6dcbb0ff42b7d4fa4c74700e and worked great

**Comment by Alexanderortizcuellar** [comment]
I'm still getting the same error

**Comment by lululoid** [comment]
> Thanks to @licy183 I have built the package after comment [63992ed](https://github.com/termux-user-repository/tur/commit/63992ed784c00b2a6dcbb0ff42b7d4fa4c74700e) and worked great

Can you provide a download link, it would be very helpful

**Comment by johndebia2022** [comment]
Here are the build artifacts.

https://github.com/termux-user-repository/tur/actions/runs/5332323143
