### ISSUE TITLE
[question] Can we make TUR be similar to NUR?

### ISSUE THREAD

**Issue by Freed-Wu** [termux-user-repository/tur#484]
<https://github.com/nix-community/NUR> collect third-party packages of NixOS, which is a combination of many users' github repositories named nur-packages. Can we make TUR be similar to NUR? Just combine many users' github repositories.

**Comment by T-Dynamos** [comment]
> many users' github repositories

Which repos you mean by? Examples?

**Comment by licy183** [comment]
Sadly, maybe not. IIUC NUR (and its repos) contains lots of scripts for users and users can compile these packages on their device. Yeah, it is possible for TUR to provide such a function. But, Termux is often used on arm devices, and compiling will cost lots of time. Actually, TUR wants to provide prebuilt binaries for users to install and save building time on arm devices.

**Comment by Freed-Wu** [comment]
> Which repos you mean by? Examples?

For example, <https://nur.nix-community.org> combines 199 user repositories currently.

> compiling will cost lots of time

Oh, I know many nur-packages use [cachix](https://app.cachix.org/) to provide binary cache. I don't know any methods to provide binary cache for termux packages. :cry:

**Comment by licy183** [comment]
Termux uses apt (or pacman), and it is much different from NixOS.

**Comment by Freed-Wu** [comment]
NUR is a combination of many users' nur-packages. There exists a CI/CD in NUR repo to combine all users' nur-package repos to one repo. every user's packages is under a namespace named `nur.user_name` to avoid conflict.

AUR is another method. AUR provide a git platform, every one can create package in AUR. once one user create repo `foo` for software foo, other user can contact him/her to send patch. create different package for same software is disencouraged.

Currently, TUR have a small amount of packages compared to AUR, so use a git repo to collect all user's packages is enough.

**Comment by Freed-Wu** [comment]
So is it possible to use it as a project template to create a customized source, user just add it to `$PREFIX/etc/apt/sources.list.d/XXX.list` to use it?
