### ISSUE TITLE
Blender need update: cannot find "libjpeg.so" from verneed[4] in DT_NEEDED list

### ISSUE THREAD

**Issue by qiangz63** [termux-user-repository/tur#487]
### Problem description

Need rebuild blender after libxml2 and libjpeg update.

### What steps will reproduce the bug?

blender

**Comment by qiangz63** [comment]
Need to rebuild `openimageio`first.

**Comment by rjshortdev** [comment]
I did the work with a fresh install of termux and termux x11.  I did a pkg update kept the package maintainer version "Y" of everything.  Then I pkg install tur-repo, pkg install x11-repo, pkg in termux-x11-nightly, pkg install build-essential  pkg install ldd, pkg install blender.  Followed this guide [ivonblog](https://ivonblog.com/en-us/posts/termux-x11/#1-install-termux-x11) to set up a xfce4 desktop.  In the xfce4 desktop env I tried to start blender got an xfce4-session-WARNING. . .CANNOT LINK EXECUTABLE "blender": cannot find "libjpeg.so" from verneed[4] in DT_NEEDED list for "/data/data/com.termux/files/usr/bin/blender"!  

I tried to rebuild openimageio from the github repo. . .mkdir build, cd build, cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX ..  

I then open blender from my xfce4 desktop got the same error "Blender":cannot find "libjpeg.so....from above.  Bummer!  I'm not experience in this so I tried to do a ldd blender.  I'm still learning about this!  Is it  supposed to link in the "libjpeg.so => /system/lib64/libjpeg.so" or should it be "libjpeg.so => /data/data/com.termux/files/usr/lib/libjpeg.so".  I'm confused?

**Comment by qiangz63** [comment]
U need to install `blender` from lastest workflow.

**Comment by qiangz63** [comment]
Should it be "libjpeg.so => /data/data/com.termux/files/usr/lib/libjpeg.so",and `libjpeg-turbo` package provided.

**Comment by qiangz63** [comment]
@T-Dynamos  Hi, need to rebuild `libraw`.

**Comment by T-Dynamos** [comment]
openimageio tested?

**Comment by qiangz63** [comment]
Run `iinfo`, CANNOT LINK EXECUTABLE "iinfo": cannot find "libjpeg.so" from verneed[0] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/libraw_r.so".

**Comment by ulist** [comment]
```
CANNOT LINK EXECUTABLE "tshark": cannot find "libxml2.so" from verneed[3] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/libwireshark.so"
```

**Comment by rjshortdev** [comment]
@qiangz63 Do I first get the deb from  [#119](https://github.com/termux-user-repository/tur/actions/runs/5543621839).  Then after that run a full install of blender or apt install --fix-broken to install the dependencies?  Rebuild openimageio, then rebuild libraw?   Is there a link to the latest build of blender with all the dependencies?  Well I'll take a breather and try again!

**Comment by T-Dynamos** [comment]
![Screenshot_20230724-073428_Termux_X11](https://github.com/termux-user-repository/tur/assets/68729523/4a5cc145-bc42-40c8-b2ff-a24420e7ff5a)

working fine again!

**Comment by qiangz63** [comment]
Thanks your job. Closed.
