### ISSUE TITLE
[Package]: zig (latest)

### ISSUE THREAD

**Issue by SunPodder** [termux-user-repository/tur#489]
### Name

zig

### Source code URL

https://github.com/ziglang/zig

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

Hey @licy183!
If you have enough free time can you have a look in this package?

A out-dated version of zig is available in termux, but the latest version have many breaking changes from that. So any new zig codebase isn’t compilable with that anymore.

I tried building it locally, the build system by default determines the target `aarch64-android` which at a later stage make the compilation process to fail. It needs to be `aarch64-linux-android`, but after changing to this I couldn’t make it find LLVM Libraries.

On CI, i got `error: unable to create compilation: FileNotFound` immediately after running `zig build`. Don’t know what caused this. I verified the `buid.zig` file was at the cwd.

**Comment by qiangz63** [comment]
Today, the lastest zig version up to v0.11.0 already could download form official site, and run fine!
I think this issue could be closed!

**Comment by SunPodder** [comment]
> Today, the lastest zig version up to v0.11.0 already could download form official site, and run fine! I think this issue could be closed!

It did compile a hello world program but running `zig libc` gives
```
error: unable to detect native libc: LibCRuntimeNotFound
```
Which may become problematic for some cases?

Also got this warning while building the program
```
warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.
```

Didn't manage to run tests
```
zig test Debug native: error: warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.
```

My primary use of zig is to build **Bun** for termux. I will try and see if this can build Bun

**Comment by nacho00112** [comment]
Please bun is being very requested

**Comment by qiangz63** [comment]
Maybe some patch,I don't know. And it looks rust build deno(similar to bun) not fine.

**Comment by licy183** [comment]
Main repo has bumped this package, see https://github.com/termux/termux-packages/pull/17733.
