### ISSUE TITLE
[Package]: Pydantic

### ISSUE THREAD

**Issue by snooppr** [termux-user-repository/tur#508]
### Name

Pydantic

### Source code URL

https://github.com/pydantic/pydantic

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

```
pydantic-core==2.3.0 (from pydantic)
  Using cached pydantic_core-2.3.0.tar.gz (308 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
```

python v3.11
python-pip v23.2.1

**Comment by 2096779623** [comment]
`CARGO_BUILD_TARGET=aarch64-linux-android pip3 install maturin==1.1.0` first.

**Comment by licy183** [comment]
Added `pydantic-core` via https://github.com/termux-user-repository/pypi-wheel-builder/commit/c6af49d5c22507f708780c8f530dd08c77ad2b1e.

Now this package is able to be installed though pip.

```
python -m pip install pydantic --extra-index-url https://termux-user-repository.github.io/pypi/
```
