### ISSUE TITLE
[Package]: yt-dlp

### ISSUE THREAD

**Issue by mid-kid** [termux-user-repository/tur#515]
### Name

yt-dlp

### Source code URL

https://github.com/yt-dlp/yt-dlp/releases

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

the termux repository contains `mpv`, and this program has support for playing music through youtube and various other services when `yt-dlp` is installed. I'd rather avoid mixing package management solutions over this...

**Comment by licy183** [comment]
This is a little hard to cross-compile on Termux...

**Comment by mid-kid** [comment]
I haven't checked, but any reason why? I thought it was a pure python package with next to no dependencies.

**Comment by licy183** [comment]
Emmm... I haven't tested whether if it possible to install this package through pip rather than do a standalone release. I'll try it this night.
