### ISSUE TITLE
[Package Help]: Hurrican

### ISSUE THREAD

**Issue by IntinteDAO** [termux-user-repository/tur#535]
### Name

Hurrican

### Source code URL

https://github.com/HurricanGame/Hurrican

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

In short Hurrican is (non-free assets) Open Source Game, Turrican like game.
The game works "nice" on Termux, but not great. Even using Mesa with DRI3 that increase much Zink performance, game have unstable FPS issue (also on virglrenderer-android). But technically game work (and maybe someone can fix it - probably a Mesa problem?? Or some other bottleneck).

Some issues:
https://github.com/HurricanGame/Hurrican
* The game files are in Hurrican directory. I just create my own package that contain only source code. So if someone can create a fix to build from this directory, it will be great.
* SDL2 linker patch. The Cmake localize SDL2 files, but Linker parameters for SDL2 are not present. I add it manually, but it's not how it should be added.

[hurrican.tar.gz](https://github.com/termux-user-repository/tur/files/12373181/hurrican.tar.gz)

**Comment by IntinteDAO** [comment]
@licy183 

Do you have a time to check it? The build chart you have on the bottom of post and it works, but need to fix some things.

Ofc. if you want

**Comment by licy183** [comment]
Hi, @IntinteDAO 

Can you test the deb files in PR 548? Thanks!

**Comment by IntinteDAO** [comment]
@licy183 

> cp: not writing through dangling symlink '/data/data/com.termux/files/usr/share/doc/hurrican/LICENSE'

Not sure if it's something on my site or in the build.sh
