### ISSUE TITLE
[Bug]: mesa-zink doesn't work on Adreno 508

### ISSUE THREAD

**Issue by Yisus7u7** [termux-user-repository/tur#560]
### Problem description

Doesn't work on Adreno 508

![Screenshot_20230902-233051_Termux](https://github.com/termux-user-repository/tur/assets/64093255/c2005a98-ad1e-4173-b079-067f42e4aa40)
![Screenshot_20230902-233149_Termux_X11](https://github.com/termux-user-repository/tur/assets/64093255/0d7e7141-737d-46e1-94c9-20e639608c79)

### What steps will reproduce the bug?

Install mesa Zink and try running glmark2 with the

### What is the expected behavior?

It should work 

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~XQD2k_hqmkvLYvISZeSXVQ==/com.termux-5xzf7lHCOAEqJimmgX86fw==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=6794
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c16,c258,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c16,c258,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10528
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.38.5
Android version:
13
Kernel build information:
Linux localhost 4.4.302-BoostKernelv0.6-g66113c45d0d6 #1 SMP PREEMPT Sun Jun 25 23:16:54 -03 2023 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(6) plus
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
```

**Comment by Yisus7u7** [comment]
![Screenshot_20230902-233358_KernelSU](https://github.com/termux-user-repository/tur/assets/64093255/9c5de63d-82e9-4dee-8f43-beacf2b7d024)
![Screenshot_20230902-233533_Termux](https://github.com/termux-user-repository/tur/assets/64093255/549b1185-209b-45de-86dc-d34133fdfc35)

I tried [this](https://github.com/ilhan-athn7/freedreno_turnip-CI) module and it still doesn't work

**Comment by IntinteDAO** [comment]
Well, not sure why do you use Freedreno driver and some strange Magisk modifications. Mesa-zink usually uses old version of Zink, that can be run using Android's Vulkan instead of Freedreno's Vulkan. If you want a Zink with Freedreno, you should use Mesa from Termux IMO.

pkg install vulkan-loader-android

And now check

**Comment by ilhan-athn7** [comment]
Alternatively you can try using Angle driver of android,
https://chromium.googlesource.com/angle/angle.git/+/HEAD/doc/DevSetupAndroid.md#angle-for-a-single-opengl-es-app
![](https://cdn.discordapp.com/attachments/642035838305435698/1118154532594131004/Screenshot_20230613-152542_GLview_Extensions_Viewer.png)

**Comment by licy183** [comment]
`mesa-zink` uses the vulkan loader provided by Android system, so I think it is intended that it doesn't work on many devices...

**Comment by Yisus7u7** [comment]
mesa does not support adreno 5xx

https://gitlab.freedesktop.org/mesa/mesa/-/issues/5491#note_1102667

angle works only with the OpenGL backend, the vulkan one does not. (it's also very slow)

**Comment by ilhan-athn7** [comment]
> mesa does not support adreno 5xx
> 
> https://gitlab.freedesktop.org/mesa/mesa/-/issues/5491#note_1102667
> 
> angle works only with the OpenGL backend, the vulkan one does not. (it's also very slow)

Angle works with Vulkan backend on android
