### ISSUE TITLE
Package request: hydra

### ISSUE THREAD

**Issue by T-Dynamos** [termux-user-repository/tur#58]
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name:hydra
Homepage:https://github.com/vanhauser-thc/thc-hydra
Source link:https://github.com/vanhauser-thc/thc-hydra/archive/refs/tags/v9.3.tar.gz

**Additional Info:**

**Comment by 2096779623** [comment]
I can build this on device, it depends on gcc, but I don't know why it builds gcc when it runs actions.😂

**Comment by licy183** [comment]
> I can build this on device, it depends on gcc, but I don't know why it builds gcc when it run github actions.😂

If you want to use gcc on device, you can try to open a Pull Request on tur-on-device.
