### ISSUE TITLE
[Package]: aicynide's all pkg request in main termux repo

### ISSUE THREAD

**Issue by aicynide** [termux-user-repository/tur#589]
### Name

https://github.com/termux/termux-packages/issues/created_by/aicynide

### Home page URL

https://github.com/termux/termux-packages/issues/created_by/aicynide

### Source code URL

https://github.com/termux/termux-packages/issues/created_by/aicynide

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by licy183** [comment]
Emmm... I'll add some of them to the official repository if they are packaged by many other Linux distros.
