### ISSUE TITLE
[Package]: VS Code (Microsoft Branded)

### ISSUE THREAD

**Issue by AmanRajAryan** [termux-user-repository/tur#599]
### Name

Visual Studio Code ( Microsoft Branded)

### Home page URL

Code.visualstudio.com

### Source code URL

https://github.com/microsoft/vscode

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by licy183** [comment]
Not possible. `Microsoft Branded` Code is only built for glibc. Maybe you need to go to [`glibc-packages`](https://github.com/termux-pacman/glibc-packages)
