### ISSUE TITLE
[Package]: RosBE

### ISSUE THREAD

**Issue by Spz2022** [termux-user-repository/tur#617]
### Name

RosBE

### Home page URL

https://reactos.org/wiki/Build_Environment

### Source code URL

https://downloads.sourceforge.net/reactos/RosBE-Unix-2.2.1.tar.bz2

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

**Comment by Spz2022** [comment]
`
~/RosBE-Unix-2.2.1 $ ./RosBE-Builder.sh ~/RosBE
*******************************************************************************
*         ReactOS Build Environment for Unix-based Operating Systems          *
*                      Builder Tool for the Base package                      *
*                      by Colin Finck <colin@reactos.org>                     *
*                                                                             *
*                                 Version 2.2.1                               *
*******************************************************************************

This script compiles and installs a complete Build Environment for building
ReactOS.

User is not "root"
The default installation path for the Build Environment is "/usr/local/RosBE".
Therefore it is recommended to run this script as the "root" user. Otherwise you probably cannot create the necessary directories.
An alternative is to specify another installation directory at the installation process.
Do you really want to continue? (yes/no)
[no] yes

Checking for the needed tools...
Checking for as... OK
Checking for bzip2... OK
Checking for find... OK
Checking for grep... OK
Checking for m4... OK
Checking for makeinfo... OK
Checking for python... OK
Checking for tar... OK
Checking for GNU Make... OK
Checking for pkg-config... OK
Checking for zlib... OK

Installation Directory
Using "/data/data/com.termux/files/home/RosBE"

Building...
Using CFLAGS="-pipe -O2 -g0 -march=native"
Using CXXFLAGS="-pipe -O2 -g0 -march=native"

Running "gcc -s -o /data/data/com.termux/files/home/RosBE/bin/cpucount /data/data/com.termux/files/home/RosBE-Unix-2.2.1/tools/cpucount.c"... OK
Running "gcc -s -o /data/data/com.termux/files/home/RosBE/bin/scut /data/data/com.termux/files/home/RosBE-Unix-2.2.1/tools/scut.c"... OK
Extracting bison... OK
Running "../bison/configure --prefix=/data/data/com.termux/files/home/RosBE --disable-nls"... OK
Running "/data/data/com.termux/files/usr/bin/make -j 9"... FAILED
Please take a look at the log file "/data/data/com.termux/files/home/RosBE-Unix-2.2.1/sources/build.log"
If you did not do something wrong, please save the log file and contact the ReactOS Team.
Aborted!
~/RosBE-Unix-2.2.1 $ cat sources/build.log
  GEN      lib/fcntl.h
  GEN      lib/textstyle.h
  GEN      lib/limits.h
  GEN      lib/alloca.h
  GEN      lib/locale.h
  GEN      lib/configmake.h
  GEN      lib/math.h
  GEN      lib/inttypes.h
  GEN      lib/sched.h
  GEN      lib/signal.h
  GEN      lib/spawn.h
  GEN      lib/stdint.h
  GEN      lib/stdio.h
  GEN      lib/stdlib.h
  GEN      lib/string.h
  GEN      lib/sys/resource.h
  GEN      lib/sys/stat.h
  GEN      lib/sys/time.h
  GEN      lib/sys/times.h
  GEN      lib/sys/types.h
  GEN      lib/time.h
  GEN      lib/sys/wait.h
  GEN      lib/unistd.h
  GEN      lib/unitypes.h
  GEN      lib/wctype.h
  GEN      lib/wchar.h
  GEN      lib/uniwidth.h
  CC       src/bison-AnnotationList.o
  CC       src/bison-assoc.o
  CC       src/bison-Sbitset.o
  CC       src/bison-InadequacyList.o
  CC       src/bison-closure.o
  CC       src/bison-derives.o
  CC       src/bison-complain.o
  CC       src/bison-conflicts.o
  CC       src/bison-files.o
  CC       src/bison-fixits.o
  CC       src/bison-getargs.o
  CC       src/bison-gram.o
  CC       src/bison-graphviz.o
  CC       src/bison-ielr.o
  CC       src/bison-lalr.o
  CC       src/bison-location.o
  CC       src/bison-lr0.o
  CC       src/bison-main.o
  CC       src/bison-muscle-tab.o
  CC       src/bison-named-ref.o
  CC       src/bison-nullable.o
  CC       src/bison-output.o
  CC       src/bison-parse-gram.o
  CC       src/bison-print-graph.o
  CC       src/bison-print-xml.o
  CC       src/bison-print.o
  CC       src/bison-reader.o
  CC       src/bison-reduce.o
  CC       src/bison-relation.o
  CC       src/bison-scan-code-c.o
  CC       src/bison-scan-gram-c.o
  CC       src/bison-scan-skel-c.o
  CC       src/bison-state.o
  CC       src/bison-symlist.o
  CC       src/bison-symtab.o
  CC       src/bison-tables.o
  CC       src/bison-uniqstr.o
  CC       lib/libbison_a-allocator.o
  CC       lib/libbison_a-areadlink.o
  CC       lib/libbison_a-argmatch.o
  CC       lib/libbison_a-gl_array_list.o
  CC       lib/libbison_a-binary-io.o
  CC       lib/libbison_a-bitrotate.o
  CC       lib/libbison_a-bitset.o
  CC       lib/bitset/libbison_a-array.o
  CC       lib/bitset/libbison_a-stats.o
  CC       lib/bitset/libbison_a-table.o
  CC       lib/bitset/libbison_a-list.o
  CC       lib/bitset/libbison_a-vector.o
  CC       lib/libbison_a-bitsetv.o
  CC       lib/libbison_a-c-ctype.o
  CC       lib/libbison_a-c-strcasecmp.o
  CC       lib/libbison_a-c-strncasecmp.o
  CC       lib/libbison_a-careadlinkat.o
  CC       lib/libbison_a-cloexec.o
  CC       lib/libbison_a-close-stream.o
  CC       lib/libbison_a-closeout.o
  CC       lib/libbison_a-concat-filename.o
  CC       lib/libbison_a-dirname.o
  CC       lib/libbison_a-basename.o
  CC       lib/libbison_a-dirname-lgpl.o
  CC       lib/libbison_a-basename-lgpl.o
  CC       lib/libbison_a-stripslash.o
  CC       lib/libbison_a-exitfail.o
  CC       lib/libbison_a-fatal-signal.o
  CC       lib/libbison_a-fd-safer-flag.o
  CC       lib/libbison_a-dup-safer-flag.o
  CC       lib/libbison_a-fopen-safer.o
  CC       lib/libbison_a-fstrcmp.o
  CC       lib/libbison_a-gethrxtime.o
  CC       lib/libbison_a-xtime.o
  CC       lib/libbison_a-getprogname.o
  CC       lib/libbison_a-gettime.o
  CC       lib/libbison_a-hard-locale.o
  CC       lib/libbison_a-hash.o
  CC       lib/libbison_a-gl_list.o
  CC       lib/libbison_a-localcharset.o
../bison/lib/hash.c:549:11: warning: implicit conversion from 'unsigned long' to 'float' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-const-int-float-conversion]
      if (SIZE_MAX <= new_candidate)
          ^~~~~~~~ ~~
./lib/stdint.h:574:21: note: expanded from macro 'SIZE_MAX'
#  define SIZE_MAX  _STDINT_MAX (0, 64, 0ul)
                    ^~~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:141:71: note: expanded from macro '_STDINT_MAX'
    (((((zero) + 1) << ((bits) ? (bits) - 1 - (signed) : 0)) - 1) * 2 + 1)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
../bison/lib/hash.c:1079:15: warning: implicit conversion from 'unsigned long' to 'float' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-const-int-float-conversion]
          if (SIZE_MAX <= candidate)
              ^~~~~~~~ ~~
./lib/stdint.h:574:21: note: expanded from macro 'SIZE_MAX'
#  define SIZE_MAX  _STDINT_MAX (0, 64, 0ul)
                    ^~~~~~~~~~~~~~~~~~~~~~~~
./lib/stdint.h:141:71: note: expanded from macro '_STDINT_MAX'
    (((((zero) + 1) << ((bits) ? (bits) - 1 - (signed) : 0)) - 1) * 2 + 1)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
  CC       lib/glthread/libbison_a-lock.o
  CC       lib/libbison_a-malloca.o
  CC       lib/libbison_a-math.o
  CC       lib/libbison_a-mbchar.o
  CC       lib/libbison_a-mbfile.o
  CC       lib/libbison_a-mbswidth.o
  CC       lib/libbison_a-pipe2.o
  CC       lib/libbison_a-pipe2-safer.o
  CC       lib/libbison_a-printf-frexp.o
2 warnings generated.
  CC       lib/libbison_a-printf-frexpl.o
  CC       lib/libbison_a-progname.o
  CC       lib/libbison_a-quotearg.o
  CC       lib/libbison_a-setlocale_null.o
  CC       lib/libbison_a-sig-handler.o
  CC       lib/libbison_a-spawn-pipe.o
  CC       lib/glthread/libbison_a-threadlib.o
  CC       lib/libbison_a-timespec.o
  CC       lib/libbison_a-timevar.o
  CC       lib/glthread/libbison_a-tls.o
  CC       lib/libbison_a-unistd.o
In file included from ../bison/lib/spawn-pipe.c:52:
./lib/spawn.h:630:17: error: use of undeclared identifier 'POSIX_SPAWN_RESETIDS'
            [(((POSIX_SPAWN_RESETIDS | POSIX_SPAWN_SETPGROUP
                ^
./lib/spawn.h  CC       lib/libbison_a-fd-safer.o
:630:40: error: use of undeclared identifier 'POSIX_SPAWN_SETPGROUP'
            [(((POSIX_SPAWN_RESETIDS | POSIX_SPAWN_SETPGROUP
                                       ^
./lib/spawn.h:631:19: error: use of undeclared identifier 'POSIX_SPAWN_SETSIGDEF'
                | POSIX_SPAWN_SETSIGDEF | POSIX_SPAWN_SETSIGMASK
                  ^
./lib/spawn.h:631:43: error: use of undeclared identifier 'POSIX_SPAWN_SETSIGMASK'
                | POSIX_SPAWN_SETSIGDEF | POSIX_SPAWN_SETSIGMASK
                                          ^
  CC       lib/libbison_a-dup-safer.o
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_RESETIDS'
               & POSIX_SPAWN_USEVFORK)
                 ^
./lib/spawn.h:618:29: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
  ((POSIX_SPAWN_RESETIDS | (POSIX_SPAWN_RESETIDS - 1)                     \
                            ^
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_RESETIDS'
./lib/spawn.h:618:5: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
  ((POSIX_SPAWN_RESETIDS | (POSIX_SPAWN_RESETIDS - 1)                     \
    ^
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_SETPGROUP'
./lib/spawn.h:619:7: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
    | POSIX_SPAWN_SETPGROUP | (POSIX_SPAWN_SETPGROUP - 1)                 \
      ^
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_SETPGROUP'
./lib/spawn.h:619:32: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
    | POSIX_SPAWN_SETPGROUP | (POSIX_SPAWN_SETPGROUP - 1)                 \
                               ^
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_SETSIGDEF'
./lib/spawn.h:620:7: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
    | POSIX_SPAWN_SETSIGDEF | (POSIX_SPAWN_SETSIGDEF - 1)                 \
      ^
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_SETSIGDEF'
./lib/spawn.h:620:32: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
    | POSIX_SPAWN_SETSIGDEF | (POSIX_SPAWN_SETSIGDEF - 1)                 \
                               ^
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_SETSIGMASK'
./lib/spawn.h:621:7: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
    | POSIX_SPAWN_SETSIGMASK | (POSIX_SPAWN_SETSIGMASK - 1)               \
      ^
./lib/spawn.h:633:18: error: use of undeclared identifier 'POSIX_SPAWN_SETSIGMASK'
./lib/spawn.h:621:33: note: expanded from macro 'POSIX_SPAWN_USEVFORK'
    | POSIX_SPAWN_SETSIGMASK | (POSIX_SPAWN_SETSIGMASK - 1)               \
                                ^
  CC       lib/libbison_a-pipe-safer.o
../bison/lib/spawn-pipe.c:334:57: error: use of undeclared identifier 'POSIX_SPAWN_SETSIGMASK'
                                                        POSIX_SPAWN_SETSIGMASK))
                                                        ^
13 errors generated.
make: *** [Makefile:5131: lib/libbison_a-spawn-pipe.o] Error 1
make: *** Waiting for unfinished jobs....
~/RosBE-Unix-2.2.1 $
`
Build log

**Comment by romanovj** [comment]
LDFLAGS=-landroid-spawn

**Comment by Spz2022** [comment]
> LDFLAGS=-landroid-spawn

../bison/lib/fprintf.c:51:7: error: call to undeclared function '__fseterr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   51 |       fseterr (fp);
      |       ^
../bison/lib/fseterr.h:29:22: note: expanded from macro 'fseterr'
   29 | # define fseterr(fp) __fseterr (fp)
      |                      ^
../bison/lib/fprintf.c:72:7: error: call to undeclared function '__fseterr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   72 |       fseterr (fp);
      |       ^
../bison/lib/fseterr.h:29:22: note: expanded from macro 'fseterr'
   29 | # define fseterr(fp) __fseterr (fp)
      |                      ^
2 errors generated.
make: *** [Makefile:5607: lib/libbison_a-fprintf.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by licy183** [comment]
This package is not able to package. It's written for GNU/Linux only.
