### ISSUE TITLE
[Question] How to exclude tur packages from regular apt updates?

### ISSUE THREAD

**Issue by SainoNamkho** [termux-user-repository/tur#632]
The connection to the tur mirror is rather slow in my region, and I frequently run `apt update` and `apt upgrade`, spending most of the time downloading from the tur mirror.

I'm wondering if there's any approach by which I can exclude tur packages while I run apt updates and upgrades, and only check for updates when I manually run specific commands like `tur update`?

**Comment by licy183** [comment]
There is no such approach currently. If you want to disable `tur-repo` temporally, you can move `$PREFIX/etc/apt/sources.list.d/tur.list` to some other location.
