### ISSUE TITLE
pygame module not found

### ISSUE THREAD

**Issue by ravener** [termux-user-repository/tur#71]
**Describe the bug**

After `apt install python-pygame`
```
~  python
Python 3.10.5 (main, Jun  7 2022, 03:53:14) [Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7 on linux
Type "help", "copyright", "credits" or "license" for more information.
i>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pygame'
>>>
```

**To Reproduce**
Describe how others will reproduce this bug. 
```
$ apt install python-pygame
$ python
>>> import pygame
```

**Expected behavior**

Pygame imports successfully.

**Screenshots**

N/A

**Termux-info**
_paste output of `termux-info` command_

N/A

**Additional context**

I tried a different package `python-pillow` and that worked fine, so I took a peek at the package script and it seems like that package adds the egg into `$PREFIX/lib/python3.10/site-packages/easy-install.pth` but the pygame module seems to have missed that step, I tried to manually append the directory into that file and it worked.

**Comment by licy183** [comment]
OK, I can confirm this issue. I will try to fix this. Thanks for reporting.

**Comment by licy183** [comment]
Should have been fixed by https://github.com/termux-user-repository/tur/commit/03818f83d7f972040f9d93d76b55df69e5c9885e.
