### ISSUE TITLE
[Bug]: pacman  gpg key import error

### ISSUE THREAD

**Issue by et2300** [termux-user-repository/tur#735]
### Problem description

@Grimler91 ping

### What steps will reproduce the bug?

![Screenshot_2023-12-19-16-34-08-91_84d3000e3f4017145260f7618db1d683](https://github.com/termux-user-repository/tur/assets/81605900/e6879117-7a96-4967-b2c7-39d3a1100e41)

### System information

termux-info:

```

```

**Comment by licy183** [comment]
CC: @Maxython

**Comment by Maxython** [comment]
@et2300, did you run the following command?
```
pacman-key --init
pacman-key --populate
```

**Comment by et2300** [comment]
ok thanks
