### ISSUE TITLE
Package request: dlib

### ISSUE THREAD

**Issue by SunPodder** [termux-user-repository/tur#74]
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name: dlib
Homepage: http://dlib.net/
Source link: https://github.com/davisking/dlib

**Additional Info:**
I tried installing dlib from pypi with `pip install dlib` it was compiling for about 2 hours and then it got killed. Please add it😑

**Comment by SunPodder** [comment]
For additional information: I successfully installed dlib, but when i import dlib it throws the below error
```
import dlib
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.10/site-packages/_dlib_pybind11.cpython-310.so"...
```

**Comment by licy183** [comment]
You can link it with `libpython3.10` using `LDFLAGS="-Wl,--no-as-needed,-lpython3.10"`. I will add it in this repo too.

**Comment by SunPodder** [comment]
Where do I set this? I tried exporting it as an environment variable but it didn't work

**Comment by T-Dynamos** [comment]
You need to rebuild it. Before build set this variable
