### ISSUE TITLE
[Bug]: Boxedwine segmentation fault when opening Wine

### ISSUE THREAD

**Issue by IntinteDAO** [termux-user-repository/tur#780]
### Problem description

I want to find out if this is a "global" problem or not. I suspect that the package has not been fully tested and you can try to write to the developer of Boxedwine for help.

In short, Boxedwine itself as a program works, but you can't run any Wine application because you get a message in the console "Segmentation Fault" (but no error in dmesg).

If anyone can check, please let us know. Then at most he will try to report the problem to boxedwine and maybe we can get help

### What steps will reproduce the bug?

Run any apps (even winemine) on Boxedwine

### What is the expected behavior?

Works? :P

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22134
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous tur-multilib
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.40.5
Android version:
13
Kernel build information:
Linux localhost 4.19.157-lineageos+ #1 SMP PREEMPT Mon Jan 1 07:33:06 UTC 2024 aarch64 Android
Device manufacturer:
motorola
Device model:
XT2125-4
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
```

**Comment by IntinteDAO** [comment]
> It is a bug of this software. You must install wine before you press some buttons.

I have Wine 6.0 in Boxedwine, but still crashing
https://tube.midov.pl/w/bHA7CJcmYHJ6bKg3A5npR6

**Comment by licy183** [comment]
It is also reproducible on Ubuntu 20.04, so this is not a bug of Termux/TUR. It should be reported upstream.

**Comment by IntinteDAO** [comment]
@licy183 Ok, I will report it, thanks. Closing (?)
