### ISSUE TITLE
[Package]: vkmark

### ISSUE THREAD

**Issue by IntinteDAO** [termux-user-repository/tur#815]
### Name

VKMark

### Home page URL

https://github.com/vkmark/vkmark

### Source code URL

https://github.com/vkmark/vkmark

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

VKMark it's something like glmark2 for Vulkan. I like benchmarks :)

This package works, but should be cleaned, maybe with automatic build. "Stable" release doesn't work for me, that's why I use master

In theory Wayland version should work, but I can't build on Docker cause wrong format issues. But usually it works great on autobuild, so maybe the scripts are better than docker's :P

[vkmark.tar.gz](https://github.com/termux-user-repository/tur/files/14214008/vkmark.tar.gz)

**Comment by licy183** [comment]
IIRC it has been packaged...

**Comment by IntinteDAO** [comment]
@licy183 :( nvm

**Comment by IntinteDAO** [comment]
@licy183 Ok, I think the package description and homepage link is bad.

**Comment by licy183** [comment]
> @licy183 Ok, I think the package description and homepage link is bad.

Fixed in https://github.com/termux-user-repository/tur/commit/b60a40a4475cbb3ed0dd17b5690ed9a190e3a8b6
