### ISSUE TITLE
Package request: Net::SSLeay Perl module

### ISSUE THREAD

**Issue by Alto1772** [termux-user-repository/tur#85]
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name: Net-SSLeay
Homepage: https://metacpan.org/dist/Net-SSLeay
Source link: https://github.com/radiator-software/p5-net-ssleay (git), https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.92.tar.gz (release)

**Additional Info:**
Before OpenSSL library on termux was upgraded to 3.x it was easy to install this module using cpan, and that came along and OpenSSL was split into two with the secure version being 1.1.x (now renamed `openssl-1.1`) and the other one 3.0.x. The former one's lib directory and include files are now located at each seperate openssl-1.1 directory. This "breaks" the Makefile.PL build script by finding the 3.x version in the lib directory and rejects it, making it to fail to build this module.

There's no scripts to setup and package Perl modules on this build system yet so I'll just leave this to you. You can look at this [Arch PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/perl-net-ssleay/trunk/PKGBUILD) for ideas, *assuming you know how to read arch linux's build system*.

**Comment by dedshit** [comment]
@Alto1772 python-cryptography works with mitmproxy ?

**Comment by T-Dynamos** [comment]
Tur already have cryptography
```
pkg i python-cryptography
```

**Comment by dedshit** [comment]
> Tur already have cryptography
> 
> ```
> pkg i python-cryptography
> ```

for me unable to install mitmproxy due to cryptography module already tried your package.

**Comment by dedshit** [comment]
> Tur already have cryptography
> 
> ```
> pkg i python-cryptography
> ```

thanks did some few tweaks by modifying cryptography module to its specific version in site-package and installed mitmproxy and works once again Thanks 👍
