### ISSUE TITLE
GH Actions Not Pulling Latest Docker Image When Building Tur-On-Device Packages

### ISSUE THREAD

**Issue by Kapral67** [termux-user-repository/tur#869]
actions still not pulling latest built image from termux-user-repoistory/termux-docker so dns resolution is failing

_Originally posted by @Kapral67 in https://github.com/termux-user-repository/tur/issues/863#issuecomment-1973558761_

We might be able to fix with something like:

```diff
index cad11a0..d3e4cb4 100755
--- a/common-files/build-termux-docker.sh
+++ b/common-files/build-termux-docker.sh
@@ -23,7 +23,8 @@ fi
 echo "Running container '$CONTAINER_NAME' from image '$TERMUX_BUILDER_IMAGE_NAME'..."

 $SUDO docker start $CONTAINER_NAME >/dev/null 2>&1 || {
-   echo "Creating new container..."
+    $SUDO docker pull $TERMUX_BUILDER_IMAGE_NAME
+    echo "Creating new container..."
    $SUDO docker run \
        --detach \
        --name $CONTAINER_NAME \
```

but I have no way to test as I only have the latest image

**Comment by licy183** [comment]
The latest image has been pulled. Removing `--network=host` should resolve this.

**Comment by Kapral67** [comment]
On my local computer, the container has dns resolution with `--network=host` set. Is this issue something specific to the github actions environment?

**Comment by licy183** [comment]
Should be fixed by https://github.com/termux-user-repository/tur/commit/3544d92b790ad7bbb6cbd0f60db937359a7a84ee

**Comment by Kapral67** [comment]
that did it, ty
