### ISSUE TITLE
[Package]: tmux with sixel support 

### ISSUE THREAD

**Issue by spanclan** [termux-user-repository/tur#886]
### Name

tmux

### Home page URL

https://github.com/tmux/tmux/wiki

### Source code URL

https://github.com/tmux/tmux

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

https://www.arewesixelyet.com/#tmux

termux-monet supports sixel rendering on the terminal and it'll be easy to navigate files and 'lsix' the images if there are any.. but sixel should be enabled with the compile flag to render on tmux.

**Comment by licy183** [comment]
I haven't installed `termux-monet`. Please test the debs in https://github.com/termux-user-repository/tur/actions/runs/8393630994.

**Comment by spanclan** [comment]
it didn't work
