### ISSUE TITLE
[Package]: dsniff

### ISSUE THREAD

**Issue by 123z45** [termux-user-repository/tur#913]
### Name

dsniff

### Home page URL

https://monkey.org/~dugsong/dsniff/

### Source code URL

https://monkey.org/~dugsong/dsniff/beta/dsniff-2.4b1.tar.gz

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

Root permission is required.
The software is old and difficult to compile.

**Comment by 123z45** [comment]
./configure --without-x --prefix=./output1 --without-db --without-libpcap --without-libnet --without-libnids
It doesn't work.
configure: error: libnids version 1.13 or greater required

**Comment by licy183** [comment]
`dsniff` has many patches to be applied. You could find them in https://ftp.debian.org/debian/pool/main/d/dsniff/dsniff_2.4b1+debian-31.debian.tar.xz.

Please test the debs in https://github.com/termux-user-repository/tur/actions/runs/8598015935. Thanks!

**Comment by 123z45** [comment]
Test passed: Android-x86 7.1 64-bit version, Android 10 arm64, Android 11 arm64

Thank you very much!
