### ISSUE TITLE
[Bug]: build rtorrent with xmlrpc support

### ISSUE THREAD

**Issue by aicynide** [termux-user-repository/tur#936]
### Problem description

We can't use rtorrent web-ui because its not built with xmlrpc support
`libxmlrpc` tarball link https://sourceforge.net/projects/xmlrpc-c/files/Xmlrpc-c%20Super%20Stable/

### What steps will reproduce the bug?

-

### System information

termux-info:

```

```

**Comment by licy183** [comment]
This should be reported in the main reporitory.
