### ISSUE TITLE
[Proposal]: Generate and report Repology metadata for TUR packages.

### ISSUE THREAD

**Issue by TomJo2000** [termux-user-repository/tur#942]
The Termux User Repository does not currently report package metadata to the Repology index,
while the main `termux/termux-packages` repo does.

Adding this should be fairly straight forward since we can mostly reuse the reporting infrastructure in use by the main repo.
https://github.com/termux/repology-metadata

One thing I'm not entirely clear on yet is if we need some sort of acknowledgement from Repology's side for this.

**Comment by licy183** [comment]
Should be fixed now.
