### ISSUE TITLE
[Package request] edex-ui

### ISSUE THREAD

**Issue by T-Dynamos** [termux-user-repository/tur#97]
- [x] I understand [TUR package policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy)

**Describe package:**
Name: edex-ui
Homepage:https://github.com/GitSquared/edex-ui
Source link: https://github.com/GitSquared/edex-ui/archive/refs/tags/v2.2.8.tar.gz

**Additional Info:**
Node?

**Comment by licy183** [comment]
This package needs electron to build, but electron depends on chromium which is not available on Termux, so let's wait.
