### ISSUE TITLE
[help on build script] filebrowser

### ISSUE THREAD

**Issue by knyipab** [termux-user-repository/tur#992]
I am drafting a build script for a new TUR package `filebrowser`: https://github.com/filebrowser/filebrowser

It provides on-of-the-box binaries (no dependencies). I don't know how to fill in SRCURL and SHA256 so that it can fit all architecture. Any suggested approach?  You may finish it and commit if you like. Thanks!

The variation in urls: 
* https://github.com/filebrowser/filebrowser/releases/download/v2.29.0/linux-arm64-filebrowser.tar.gz
* https://github.com/filebrowser/filebrowser/releases/download/v2.29.0/linux-armv7-filebrowser.tar.gz
* https://github.com/filebrowser/filebrowser/releases/download/v2.29.0/linux-amd64-filebrowser.tar.gz
* https://github.com/filebrowser/filebrowser/releases/download/v2.29.0/linux-386-filebrowser.tar.gz

```bash
TERMUX_PKG_HOMEPAGE=https://filebrowser.org/
TERMUX_PKG_DESCRIPTION="Web file browser based on Go"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux-user-repository"
TERMUX_PKG_VERSION="2.29.0"
TERMUX_PKG_SRCURL=
TERMUX_PKG_SHA256=
TERMUX_PKG_AUTO_UPDATE=true

// termux_step_get_source() {
//                
// }

termux_step_make_install() {
               install -Dm700 "${TERMUX_PKG_SRCDIR}/filebrowser" "${TERMUX_PREFIX}/bin/filebrowser"
}
```

**Comment by licy183** [comment]
It is written in Golang. I recommend rebuilding this package using the building system to avoid possible DNS issues.

**Comment by knyipab** [comment]
Okay and made PR #998
